exports.Products = [
  {
    OtherStartups: "",
    ProductName: "",
    ProductID: "",
    Category: "",
    SubCategory: "",
    SubSubCategory: "",
    Unit: "",
    Breakqty: "",
    Price: "",
    Limit: "",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Onion",
    ProductID: "A0101",
    Category: "Vegetables & Fruits",
    SubCategory: "Fresh Vegetables",
    SubSubCategory: "",
    Unit: "KG",
    Breakqty: "1",
    Price: "25",
    Limit: "4",
    Trending: "0",
    "": "",
    Grofers: "",
    Bigbasket: "35",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Potato",
    ProductID: "A0102",
    Category: "Vegetables & Fruits",
    SubCategory: "Fresh Vegetables",
    SubSubCategory: "",
    Unit: "KG",
    Breakqty: "1",
    Price: "26",
    Limit: "4",
    Trending: "0",
    "": "",
    Grofers: "",
    Bigbasket: "32",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Cauliflower",
    ProductID: "A0103",
    Category: "Vegetables & Fruits",
    SubCategory: "Fresh Vegetables",
    SubSubCategory: "",
    Unit: "PCS",
    Breakqty: "1",
    Price: "27",
    Limit: "4",
    Trending: "1",
    "": "",
    Grofers: "",
    Bigbasket: "22",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Tomato-Hybrid",
    ProductID: "A0104",
    Category: "Vegetables & Fruits",
    SubCategory: "Fresh Vegetables",
    SubSubCategory: "",
    Unit: "KG",
    Breakqty: "1",
    Price: "28",
    Limit: "4",
    Trending: "1",
    "": "",
    Grofers: "",
    Bigbasket: "32",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Tomato-Desi",
    ProductID: "A0105",
    Category: "Vegetables & Fruits",
    SubCategory: "Fresh Vegetables",
    SubSubCategory: "",
    Unit: "KG",
    Breakqty: "1",
    Price: "29",
    Limit: "4",
    Trending: "0",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Ladies Finger",
    ProductID: "A0106",
    Category: "Vegetables & Fruits",
    SubCategory: "Fresh Vegetables",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "500",
    Price: "30",
    Limit: "4",
    Trending: "1",
    "": "",
    Grofers: "",
    Bigbasket: "45",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Capsicum-Green",
    ProductID: "A0107",
    Category: "Vegetables & Fruits",
    SubCategory: "Fresh Vegetables",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "500",
    Price: "31",
    Limit: "4",
    Trending: "1",
    "": "",
    Grofers: "",
    Bigbasket: "30",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Spinach",
    ProductID: "A0108",
    Category: "Vegetables & Fruits",
    SubCategory: "Fresh Vegetables",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "500",
    Price: "32",
    Limit: "4",
    Trending: "1",
    "": "",
    Grofers: "",
    Bigbasket: "20",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Cucumber- Desi",
    ProductID: "A0109",
    Category: "Vegetables & Fruits",
    SubCategory: "Fresh Vegetables",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "500",
    Price: "33",
    Limit: "4",
    Trending: "1",
    "": "",
    Grofers: "",
    Bigbasket: "8",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Bottle Gourd",
    ProductID: "A0110",
    Category: "Vegetables & Fruits",
    SubCategory: "Fresh Vegetables",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "500",
    Price: "34",
    Limit: "4",
    Trending: "1",
    "": "",
    Grofers: "",
    Bigbasket: "18",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Cabbage",
    ProductID: "A0111",
    Category: "Vegetables & Fruits",
    SubCategory: "Fresh Vegetables",
    SubSubCategory: "",
    Unit: "PCS",
    Breakqty: "1",
    Price: "35",
    Limit: "4",
    Trending: "1",
    "": "",
    Grofers: "",
    Bigbasket: "15",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Beetroot",
    ProductID: "A0112",
    Category: "Vegetables & Fruits",
    SubCategory: "Fresh Vegetables",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "36",
    Limit: "4",
    Trending: "0",
    "": "",
    Grofers: "",
    Bigbasket: "12",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Bitter Gourd",
    ProductID: "A0113",
    Category: "Vegetables & Fruits",
    SubCategory: "Fresh Vegetables",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "37",
    Limit: "4",
    Trending: "0",
    "": "",
    Grofers: "",
    Bigbasket: "18",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Colocasia",
    ProductID: "A0114",
    Category: "Vegetables & Fruits",
    SubCategory: "Fresh Vegetables",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "500",
    Price: "38",
    Limit: "4",
    Trending: "0",
    "": "",
    Grofers: "",
    Bigbasket: "50",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Brinjal- Purple Bharta",
    ProductID: "A0115",
    Category: "Vegetables & Fruits",
    SubCategory: "Fresh Vegetables",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "500",
    Price: "39",
    Limit: "4",
    Trending: "0",
    "": "",
    Grofers: "",
    Bigbasket: "25",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Pumpkin-Red",
    ProductID: "A0116",
    Category: "Vegetables & Fruits",
    SubCategory: "Fresh Vegetables",
    SubSubCategory: "",
    Unit: "KG",
    Breakqty: "1",
    Price: "40",
    Limit: "4",
    Trending: "1",
    "": "",
    Grofers: "",
    Bigbasket: "43",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Carrot-Red",
    ProductID: "A0117",
    Category: "Vegetables & Fruits",
    SubCategory: "Fresh Vegetables",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "500",
    Price: "41",
    Limit: "4",
    Trending: "0",
    "": "",
    Grofers: "",
    Bigbasket: "NA",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Parwal",
    ProductID: "A0118",
    Category: "Vegetables & Fruits",
    SubCategory: "Fresh Vegetables",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "500",
    Price: "42",
    Limit: "4",
    Trending: "1",
    "": "",
    Grofers: "",
    Bigbasket: "46",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Sponge Gourd",
    ProductID: "A0119",
    Category: "Vegetables & Fruits",
    SubCategory: "Fresh Vegetables",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "500",
    Price: "43",
    Limit: "4",
    Trending: "0",
    "": "",
    Grofers: "",
    Bigbasket: "42",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Kakdi",
    ProductID: "A0120",
    Category: "Vegetables & Fruits",
    SubCategory: "Fresh Vegetables",
    SubSubCategory: "",
    Unit: "KG",
    Breakqty: "1",
    Price: "44",
    Limit: "4",
    Trending: "0",
    "": "",
    Grofers: "",
    Bigbasket: "35",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Green Peas",
    ProductID: "A0121",
    Category: "Vegetables & Fruits",
    SubCategory: "Fresh Vegetables",
    SubSubCategory: "",
    Unit: "KG",
    Breakqty: "1",
    Price: "45",
    Limit: "4",
    Trending: "1",
    "": "",
    Grofers: "",
    Bigbasket: "96",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Beans- Broad",
    ProductID: "A0122",
    Category: "Vegetables & Fruits",
    SubCategory: "Fresh Vegetables",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "500",
    Price: "46",
    Limit: "4",
    Trending: "0",
    "": "",
    Grofers: "",
    Bigbasket: "34",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Brinjal- Purple Long",
    ProductID: "A0123",
    Category: "Vegetables & Fruits",
    SubCategory: "Fresh Vegetables",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "500",
    Price: "47",
    Limit: "4",
    Trending: "1",
    "": "",
    Grofers: "",
    Bigbasket: "29",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Beans-French, Ring",
    ProductID: "A0124",
    Category: "Vegetables & Fruits",
    SubCategory: "Fresh Vegetables",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "500",
    Price: "48",
    Limit: "4",
    Trending: "1",
    "": "",
    Grofers: "",
    Bigbasket: "31",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Pumpkin-Disco",
    ProductID: "A0125",
    Category: "Vegetables & Fruits",
    SubCategory: "Fresh Vegetables",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "500",
    Price: "49",
    Limit: "4",
    Trending: "0",
    "": "",
    Grofers: "",
    Bigbasket: "10",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Ginger",
    ProductID: "A0201",
    Category: "Vegetables & Fruits",
    SubCategory: "Herbs & Seasonings",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "50",
    Limit: "4",
    Trending: "1",
    "": "",
    Grofers: "",
    Bigbasket: "42",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Lemon",
    ProductID: "A0202",
    Category: "Vegetables & Fruits",
    SubCategory: "Herbs & Seasonings",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "51",
    Limit: "4",
    Trending: "1",
    "": "",
    Grofers: "",
    Bigbasket: "37.5",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Garlic",
    ProductID: "A0203",
    Category: "Vegetables & Fruits",
    SubCategory: "Herbs & Seasonings",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "52",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "50",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Chilli-Green",
    ProductID: "A0204",
    Category: "Vegetables & Fruits",
    SubCategory: "Herbs & Seasonings",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "53",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "25",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Corriander Leaves",
    ProductID: "A0205",
    Category: "Vegetables & Fruits",
    SubCategory: "Herbs & Seasonings",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "54",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "13",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Mint Leaves",
    ProductID: "A0206",
    Category: "Vegetables & Fruits",
    SubCategory: "Herbs & Seasonings",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "55",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "27",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Broccoli",
    ProductID: "A0301",
    Category: "Vegetables & Fruits",
    SubCategory: "Exotic Vegetables",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "500",
    Price: "56",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "56",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Spring Onion",
    ProductID: "A0302",
    Category: "Vegetables & Fruits",
    SubCategory: "Exotic Vegetables",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "500",
    Price: "57",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "23",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Cumumber-English",
    ProductID: "A0303",
    Category: "Vegetables & Fruits",
    SubCategory: "Exotic Vegetables",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "500",
    Price: "58",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "19",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Capsicum-Yellow",
    ProductID: "A0304",
    Category: "Vegetables & Fruits",
    SubCategory: "Exotic Vegetables",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "59",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "25",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Lettuce",
    ProductID: "A0305",
    Category: "Vegetables & Fruits",
    SubCategory: "Exotic Vegetables",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "500",
    Price: "60",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "25",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Sweet Corn",
    ProductID: "A0306",
    Category: "Vegetables & Fruits",
    SubCategory: "Exotic Vegetables",
    SubSubCategory: "",
    Unit: "PCS",
    Breakqty: "1",
    Price: "61",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "23.5",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Zucchini- Yellow",
    ProductID: "A0307",
    Category: "Vegetables & Fruits",
    SubCategory: "Exotic Vegetables",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "500",
    Price: "62",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "38",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Mushroom- White Button",
    ProductID: "A0308",
    Category: "Vegetables & Fruits",
    SubCategory: "Exotic Vegetables",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "63",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "NA",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Zucchini- Green",
    ProductID: "A0309",
    Category: "Vegetables & Fruits",
    SubCategory: "Exotic Vegetables",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "500",
    Price: "64",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "35",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Capsicum-Red",
    ProductID: "A0310",
    Category: "Vegetables & Fruits",
    SubCategory: "Exotic Vegetables",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "65",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "25",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Banana",
    ProductID: "A0401",
    Category: "Vegetables & Fruits",
    SubCategory: "Fresh Fruits",
    SubSubCategory: "",
    Unit: "PCS",
    Breakqty: "6",
    Price: "66",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "57/kg",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Grapes-Green Seedless",
    ProductID: "A0402",
    Category: "Vegetables & Fruits",
    SubCategory: "Fresh Fruits",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "500",
    Price: "67",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "70",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Pomegranate",
    ProductID: "A0403",
    Category: "Vegetables & Fruits",
    SubCategory: "Fresh Fruits",
    SubSubCategory: "",
    Unit: "PCS",
    Breakqty: "4",
    Price: "68",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "149",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Orange- Nagpur,Regular",
    ProductID: "A0404",
    Category: "Vegetables & Fruits",
    SubCategory: "Fresh Fruits",
    SubSubCategory: "",
    Unit: "KG",
    Breakqty: "1",
    Price: "69",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "79",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Apple- Red Delicious/Washington",
    ProductID: "A0405",
    Category: "Vegetables & Fruits",
    SubCategory: "Fresh Fruits",
    SubSubCategory: "",
    Unit: "PCS",
    Breakqty: "4",
    Price: "70",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "165",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Papaya",
    ProductID: "A0406",
    Category: "Vegetables & Fruits",
    SubCategory: "Fresh Fruits",
    SubSubCategory: "",
    Unit: "PCS",
    Breakqty: "1",
    Price: "71",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "80",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Apple- Shimla",
    ProductID: "A0407",
    Category: "Vegetables & Fruits",
    SubCategory: "Fresh Fruits",
    SubSubCategory: "",
    Unit: "PCS",
    Breakqty: "4",
    Price: "72",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "99",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Grapes-Black Seedless",
    ProductID: "A0408",
    Category: "Vegetables & Fruits",
    SubCategory: "Fresh Fruits",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "500",
    Price: "73",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Apple- Royal Gala",
    ProductID: "A0409",
    Category: "Vegetables & Fruits",
    SubCategory: "Fresh Fruits",
    SubSubCategory: "",
    Unit: "PCS",
    Breakqty: "4",
    Price: "74",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "165",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Gauva",
    ProductID: "A0410",
    Category: "Vegetables & Fruits",
    SubCategory: "Fresh Fruits",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "500",
    Price: "75",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "NA",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Mango-Safeda",
    ProductID: "A0411",
    Category: "Vegetables & Fruits",
    SubCategory: "Fresh Fruits",
    SubSubCategory: "",
    Unit: "KG",
    Breakqty: "1",
    Price: "76",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "119",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Watermelon",
    ProductID: "A0412",
    Category: "Vegetables & Fruits",
    SubCategory: "Fresh Fruits",
    SubSubCategory: "",
    Unit: "PCS",
    Breakqty: "1",
    Price: "77",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "55",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Coconut",
    ProductID: "A0413",
    Category: "Vegetables & Fruits",
    SubCategory: "Fresh Fruits",
    SubSubCategory: "",
    Unit: "PCS",
    Breakqty: "1",
    Price: "78",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "42",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Pineapple",
    ProductID: "A0414",
    Category: "Vegetables & Fruits",
    SubCategory: "Fresh Fruits",
    SubSubCategory: "",
    Unit: "PCS",
    Breakqty: "1",
    Price: "79",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "58",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Apple-Fuji",
    ProductID: "A0415",
    Category: "Vegetables & Fruits",
    SubCategory: "Fresh Fruits",
    SubSubCategory: "",
    Unit: "PCS",
    Breakqty: "4",
    Price: "80",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "189",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Kiwi-Green",
    ProductID: "A0501",
    Category: "Vegetables & Fruits",
    SubCategory: "Exotic Fruits",
    SubSubCategory: "",
    Unit: "PCS",
    Breakqty: "4",
    Price: "81",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "119",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Grapes-Red Globe",
    ProductID: "A0502",
    Category: "Vegetables & Fruits",
    SubCategory: "Exotic Fruits",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "82",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "130",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Strawberry",
    ProductID: "A0503",
    Category: "Vegetables & Fruits",
    SubCategory: "Exotic Fruits",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "83",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "NA",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Tender Coconut",
    ProductID: "A0504",
    Category: "Vegetables & Fruits",
    SubCategory: "Exotic Fruits",
    SubSubCategory: "",
    Unit: "PCS",
    Breakqty: "1",
    Price: "84",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "49",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Pears",
    ProductID: "A0505",
    Category: "Vegetables & Fruits",
    SubCategory: "Exotic Fruits",
    SubSubCategory: "",
    Unit: "PCS",
    Breakqty: "4",
    Price: "85",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "199",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Muskmelon",
    ProductID: "A0506",
    Category: "Vegetables & Fruits",
    SubCategory: "Exotic Fruits",
    SubSubCategory: "",
    Unit: "PCS",
    Breakqty: "1",
    Price: "86",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "69",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Ashirwad Atta",
    ProductID: "B0101",
    Category: "Food Grains, Oil & Masala",
    SubCategory: "Atta, Flour & Sooji",
    SubSubCategory: "",
    Unit: "KG",
    Breakqty: "5",
    Price: "87",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Rajdhani Sooji",
    ProductID: "B0102",
    Category: "Food Grains, Oil & Masala",
    SubCategory: "Atta, Flour & Sooji",
    SubSubCategory: "",
    Unit: "KG",
    Breakqty: "1",
    Price: "88",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Rajdhani Besan",
    ProductID: "B0103",
    Category: "Food Grains, Oil & Masala",
    SubCategory: "Atta, Flour & Sooji",
    SubSubCategory: "",
    Unit: "KG",
    Breakqty: "1",
    Price: "89",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Rajhani Maida",
    ProductID: "B0104",
    Category: "Food Grains, Oil & Masala",
    SubCategory: "Atta, Flour & Sooji",
    SubSubCategory: "",
    Unit: "KG",
    Breakqty: "1",
    Price: "90",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Chakki Atta",
    ProductID: "B0105",
    Category: "Food Grains, Oil & Masala",
    SubCategory: "Atta, Flour & Sooji",
    SubSubCategory: "",
    Unit: "KG",
    Breakqty: "1",
    Price: "91",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Arhar Daal",
    ProductID: "B0201",
    Category: "Food Grains, Oil & Masala",
    SubCategory: "Dals & Pulses",
    SubSubCategory: "",
    Unit: "KG",
    Breakqty: "1",
    Price: "92",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Urad Daal",
    ProductID: "B0202",
    Category: "Food Grains, Oil & Masala",
    SubCategory: "Dals & Pulses",
    SubSubCategory: "",
    Unit: "KG",
    Breakqty: "1",
    Price: "93",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Moong Dal",
    ProductID: "B0203",
    Category: "Food Grains, Oil & Masala",
    SubCategory: "Dals & Pulses",
    SubSubCategory: "",
    Unit: "KG",
    Breakqty: "1",
    Price: "94",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Rajma",
    ProductID: "B0204",
    Category: "Food Grains, Oil & Masala",
    SubCategory: "Dals & Pulses",
    SubSubCategory: "",
    Unit: "KG",
    Breakqty: "1",
    Price: "95",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Chana",
    ProductID: "B0205",
    Category: "Food Grains, Oil & Masala",
    SubCategory: "Dals & Pulses",
    SubSubCategory: "",
    Unit: "KG",
    Breakqty: "1",
    Price: "96",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Daawat Rozana Super Basmati Rice",
    ProductID: "B0301",
    Category: "Food Grains, Oil & Masala",
    SubCategory: "Rice & Rice Products",
    SubSubCategory: "",
    Unit: "KG",
    Breakqty: "1",
    Price: "97",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Daawat Rozana Gold Basmati Rice",
    ProductID: "B0302",
    Category: "Food Grains, Oil & Masala",
    SubCategory: "Rice & Rice Products",
    SubSubCategory: "",
    Unit: "KG",
    Breakqty: "1",
    Price: "98",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Family fresh Broken Rice",
    ProductID: "B0303",
    Category: "Food Grains, Oil & Masala",
    SubCategory: "Rice & Rice Products",
    SubSubCategory: "",
    Unit: "KG",
    Breakqty: "1",
    Price: "99",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "India Gate Long Basmati Rice",
    ProductID: "B0304",
    Category: "Food Grains, Oil & Masala",
    SubCategory: "Rice & Rice Products",
    SubSubCategory: "",
    Unit: "KG",
    Breakqty: "1",
    Price: "100",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Fortune Soyabean Oil",
    ProductID: "B0401",
    Category: "Food Grains, Oil & Masala",
    SubCategory: "Edible Oils, Ghee & Vinegar",
    SubSubCategory: "",
    Unit: "KG",
    Breakqty: "1",
    Price: "101",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Fortune Sunflower Oil",
    ProductID: "B0402",
    Category: "Food Grains, Oil & Masala",
    SubCategory: "Edible Oils, Ghee & Vinegar",
    SubSubCategory: "",
    Unit: "KG",
    Breakqty: "1",
    Price: "102",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Soffola Gold Pro Oil",
    ProductID: "B0403",
    Category: "Food Grains, Oil & Masala",
    SubCategory: "Edible Oils, Ghee & Vinegar",
    SubSubCategory: "",
    Unit: "KG",
    Breakqty: "1",
    Price: "103",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Patanjali Ghee",
    ProductID: "B0404",
    Category: "Food Grains, Oil & Masala",
    SubCategory: "Edible Oils, Ghee & Vinegar",
    SubSubCategory: "",
    Unit: "KG",
    Breakqty: "1",
    Price: "104",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Extra Virgin Olive Oil",
    ProductID: "B0405",
    Category: "Food Grains, Oil & Masala",
    SubCategory: "Edible Oils, Ghee & Vinegar",
    SubSubCategory: "",
    Unit: "KG",
    Breakqty: "1",
    Price: "105",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Catch Haldi Powder",
    ProductID: "B0501",
    Category: "Food Grains, Oil & Masala",
    SubCategory: "Masala & Spices",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "106",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Catch Laal Mirch Powder",
    ProductID: "B0502",
    Category: "Food Grains, Oil & Masala",
    SubCategory: "Masala & Spices",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "107",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Catch Dhaniya Powder",
    ProductID: "B0503",
    Category: "Food Grains, Oil & Masala",
    SubCategory: "Masala & Spices",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "108",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "MDH Kashmiri Mirch Powder",
    ProductID: "B0504",
    Category: "Food Grains, Oil & Masala",
    SubCategory: "Masala & Spices",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "109",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Mawana Premium Sugar",
    ProductID: "B0601",
    Category: "Food Grains, Oil & Masala",
    SubCategory: "Salt, Sugar & Dry Fruits",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "500",
    Price: "110",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Tata Salt",
    ProductID: "B0602",
    Category: "Food Grains, Oil & Masala",
    SubCategory: "Salt, Sugar & Dry Fruits",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "500",
    Price: "111",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Mother Choice Almonds",
    ProductID: "B0603",
    Category: "Food Grains, Oil & Masala",
    SubCategory: "Salt, Sugar & Dry Fruits",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "500",
    Price: "112",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Mother Choice Cashew",
    ProductID: "B0604",
    Category: "Food Grains, Oil & Masala",
    SubCategory: "Salt, Sugar & Dry Fruits",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "500",
    Price: "113",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Amul Full Cream Milk",
    ProductID: "C0101",
    Category: "Bakery & Dairy Products",
    SubCategory: "Dairy Products",
    SubSubCategory: "",
    Unit: "ML",
    Breakqty: "250",
    Price: "114",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Amul Toned Milk",
    ProductID: "C0102",
    Category: "Bakery & Dairy Products",
    SubCategory: "Dairy Products",
    SubSubCategory: "",
    Unit: "ML",
    Breakqty: "250",
    Price: "115",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Mother Dairy Double Toned Milk",
    ProductID: "C0103",
    Category: "Bakery & Dairy Products",
    SubCategory: "Dairy Products",
    SubSubCategory: "",
    Unit: "ML",
    Breakqty: "250",
    Price: "116",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Amul Dahi",
    ProductID: "C0104",
    Category: "Bakery & Dairy Products",
    SubCategory: "Dairy Products",
    SubSubCategory: "",
    Unit: "ML",
    Breakqty: "250",
    Price: "117",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Mother Dairy Masala Chaach",
    ProductID: "C0105",
    Category: "Bakery & Dairy Products",
    SubCategory: "Dairy Products",
    SubSubCategory: "",
    Unit: "ML",
    Breakqty: "250",
    Price: "118",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Golden Harvest White Bread",
    ProductID: "C0201",
    Category: "Bakery & Dairy Products",
    SubCategory: "Bread & Buns",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "119",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Golden Harvest Brown Bread",
    ProductID: "C0202",
    Category: "Bakery & Dairy Products",
    SubCategory: "Bread & Buns",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "120",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "English Oven Multigrain Bread",
    ProductID: "C0203",
    Category: "Bakery & Dairy Products",
    SubCategory: "Bread & Buns",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "121",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "English Oven Burger Buns",
    ProductID: "C0204",
    Category: "Bakery & Dairy Products",
    SubCategory: "Bread & Buns",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "122",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Coconut Cookies",
    ProductID: "C0301",
    Category: "Bakery & Dairy Products",
    SubCategory: "Cookies & Backery Snacks",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "123",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Baked Jeera Cookies",
    ProductID: "C0302",
    Category: "Bakery & Dairy Products",
    SubCategory: "Cookies & Backery Snacks",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "124",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Bread Loaf",
    ProductID: "C0303",
    Category: "Bakery & Dairy Products",
    SubCategory: "Cookies & Backery Snacks",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "125",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Garlic Bread Loaf",
    ProductID: "C0304",
    Category: "Bakery & Dairy Products",
    SubCategory: "Cookies & Backery Snacks",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "126",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Wagh Bakri Premium Tea",
    ProductID: "D0101",
    Category: "Beverages",
    SubCategory: "Tea",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "500",
    Price: "127",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Tetley Lemon Green Tee",
    ProductID: "D0102",
    Category: "Beverages",
    SubCategory: "Tea",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "500",
    Price: "128",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Tata Premium Tea",
    ProductID: "D0103",
    Category: "Beverages",
    SubCategory: "Tea",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "500",
    Price: "129",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Glucon-D Orange",
    ProductID: "D0104",
    Category: "Beverages",
    SubCategory: "Tea",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "500",
    Price: "130",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Cadbury Bournvita",
    ProductID: "D0105",
    Category: "Beverages",
    SubCategory: "Tea",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "500",
    Price: "131",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Nescafe Classic Coffee",
    ProductID: "D0201",
    Category: "Beverages",
    SubCategory: "Coffee",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "500",
    Price: "132",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Bru Preimum Coffee",
    ProductID: "D0202",
    Category: "Beverages",
    SubCategory: "Coffee",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "500",
    Price: "133",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Bru Instant Coffee",
    ProductID: "D0203",
    Category: "Beverages",
    SubCategory: "Coffee",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "500",
    Price: "134",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Thumps Up",
    ProductID: "D0301",
    Category: "Beverages",
    SubCategory: "Soft Drinks & Soda",
    SubSubCategory: "",
    Unit: "ML",
    Breakqty: "500",
    Price: "135",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Miranda",
    ProductID: "D0302",
    Category: "Beverages",
    SubCategory: "Soft Drinks & Soda",
    SubSubCategory: "",
    Unit: "ML",
    Breakqty: "500",
    Price: "136",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Limca",
    ProductID: "D0303",
    Category: "Beverages",
    SubCategory: "Soft Drinks & Soda",
    SubSubCategory: "",
    Unit: "ML",
    Breakqty: "500",
    Price: "137",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Pepsi",
    ProductID: "D0304",
    Category: "Beverages",
    SubCategory: "Soft Drinks & Soda",
    SubSubCategory: "",
    Unit: "ML",
    Breakqty: "500",
    Price: "138",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Complan",
    ProductID: "D0401",
    Category: "Beverages",
    SubCategory: "Health Drinks",
    SubSubCategory: "",
    Unit: "ML",
    Breakqty: "500",
    Price: "139",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Boost",
    ProductID: "D0402",
    Category: "Beverages",
    SubCategory: "Health Drinks",
    SubSubCategory: "",
    Unit: "ML",
    Breakqty: "500",
    Price: "140",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Horlicks",
    ProductID: "D0403",
    Category: "Beverages",
    SubCategory: "Health Drinks",
    SubSubCategory: "",
    Unit: "ML",
    Breakqty: "500",
    Price: "141",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Milo",
    ProductID: "D0404",
    Category: "Beverages",
    SubCategory: "Health Drinks",
    SubSubCategory: "",
    Unit: "ML",
    Breakqty: "500",
    Price: "142",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Real Mix Fruit Juice",
    ProductID: "D0501",
    Category: "Beverages",
    SubCategory: "Fruit Juices & Drinks",
    SubSubCategory: "",
    Unit: "ML",
    Breakqty: "250",
    Price: "143",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Tropicana Orange Juice",
    ProductID: "D0502",
    Category: "Beverages",
    SubCategory: "Fruit Juices & Drinks",
    SubSubCategory: "",
    Unit: "ML",
    Breakqty: "250",
    Price: "144",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Real Mango Juice",
    ProductID: "D0503",
    Category: "Beverages",
    SubCategory: "Fruit Juices & Drinks",
    SubSubCategory: "",
    Unit: "ML",
    Breakqty: "250",
    Price: "145",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Real Raspberry Juice",
    ProductID: "D0504",
    Category: "Beverages",
    SubCategory: "Fruit Juices & Drinks",
    SubSubCategory: "",
    Unit: "ML",
    Breakqty: "250",
    Price: "146",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Bisleri Water",
    ProductID: "D0601",
    Category: "Beverages",
    SubCategory: "Water",
    SubSubCategory: "",
    Unit: "ML",
    Breakqty: "250",
    Price: "147",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Mountain Water",
    ProductID: "D0602",
    Category: "Beverages",
    SubCategory: "Water",
    SubSubCategory: "",
    Unit: "ML",
    Breakqty: "250",
    Price: "148",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Baliey Water",
    ProductID: "D0603",
    Category: "Beverages",
    SubCategory: "Water",
    SubSubCategory: "",
    Unit: "ML",
    Breakqty: "250",
    Price: "149",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "McDowells Water",
    ProductID: "D0604",
    Category: "Beverages",
    SubCategory: "Water",
    SubSubCategory: "",
    Unit: "ML",
    Breakqty: "250",
    Price: "150",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Maggi Masala Noodles",
    ProductID: "E0101",
    Category: "Snacks & Instant Foods",
    SubCategory: "Noodles & Pasta",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "151",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Sunfeast Yipee",
    ProductID: "E0102",
    Category: "Snacks & Instant Foods",
    SubCategory: "Noodles & Pasta",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "152",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Maggi Atta Noodles",
    ProductID: "E0103",
    Category: "Snacks & Instant Foods",
    SubCategory: "Noodles & Pasta",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "153",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Chings Garlic Noodles",
    ProductID: "E0104",
    Category: "Snacks & Instant Foods",
    SubCategory: "Noodles & Pasta",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "154",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Soffola Oats",
    ProductID: "E0201",
    Category: "Snacks & Instant Foods",
    SubCategory: "Breakfast & Cereals",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "155",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Kellog Museli",
    ProductID: "E0202",
    Category: "Snacks & Instant Foods",
    SubCategory: "Breakfast & Cereals",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "156",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Kellog Cereals",
    ProductID: "E0203",
    Category: "Snacks & Instant Foods",
    SubCategory: "Breakfast & Cereals",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "157",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Fruit Loops",
    ProductID: "E0204",
    Category: "Snacks & Instant Foods",
    SubCategory: "Breakfast & Cereals",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "158",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Sunfeast Coconut Cookies",
    ProductID: "E0301",
    Category: "Snacks & Instant Foods",
    SubCategory: "Buscuits & Cookies",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "159",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "ITC Dark Fantasy",
    ProductID: "E0302",
    Category: "Snacks & Instant Foods",
    SubCategory: "Buscuits & Cookies",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "160",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Parle Hide & Seek",
    ProductID: "E0303",
    Category: "Snacks & Instant Foods",
    SubCategory: "Buscuits & Cookies",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "161",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Good Day Kaju",
    ProductID: "E0304",
    Category: "Snacks & Instant Foods",
    SubCategory: "Buscuits & Cookies",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "162",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Peas",
    ProductID: "E0401",
    Category: "Snacks & Instant Foods",
    SubCategory: "Frozen Veggies & Snacks",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "163",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "McCean Similies",
    ProductID: "E0402",
    Category: "Snacks & Instant Foods",
    SubCategory: "Frozen Veggies & Snacks",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "164",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "McCean Sausages",
    ProductID: "E0403",
    Category: "Snacks & Instant Foods",
    SubCategory: "Frozen Veggies & Snacks",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "165",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "McCean Aloo Patty",
    ProductID: "E0404",
    Category: "Snacks & Instant Foods",
    SubCategory: "Frozen Veggies & Snacks",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "166",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Heinz Tomato Ketchup",
    ProductID: "E0501",
    Category: "Snacks & Instant Foods",
    SubCategory: "Spreads, Sauces & Ketchup",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "167",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Kissan Tomato Ketchup",
    ProductID: "E0502",
    Category: "Snacks & Instant Foods",
    SubCategory: "Spreads, Sauces & Ketchup",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "168",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Maggi Tomato Ketchup",
    ProductID: "E0503",
    Category: "Snacks & Instant Foods",
    SubCategory: "Spreads, Sauces & Ketchup",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "169",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Viba Mustard Spread",
    ProductID: "E0504",
    Category: "Snacks & Instant Foods",
    SubCategory: "Spreads, Sauces & Ketchup",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "170",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Viba mayonesse",
    ProductID: "E0505",
    Category: "Snacks & Instant Foods",
    SubCategory: "Spreads, Sauces & Ketchup",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "171",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Haldiram Aloo Bhujia",
    ProductID: "E0601",
    Category: "Snacks & Instant Foods",
    SubCategory: "Snacks & Namkeem",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "172",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Haldiram Besan Bhujia",
    ProductID: "E0602",
    Category: "Snacks & Instant Foods",
    SubCategory: "Snacks & Namkeem",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "173",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Haldiram Khatta Mitta",
    ProductID: "E0603",
    Category: "Snacks & Instant Foods",
    SubCategory: "Snacks & Namkeem",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "174",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Bikano Punjabi Mix",
    ProductID: "E0604",
    Category: "Snacks & Instant Foods",
    SubCategory: "Snacks & Namkeem",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "175",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Maggi Cup Noodles",
    ProductID: "E0701",
    Category: "Snacks & Instant Foods",
    SubCategory: "Ready to Eat",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "176",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Sunfeast Mushroom Pasta",
    ProductID: "E0702",
    Category: "Snacks & Instant Foods",
    SubCategory: "Ready to Eat",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "177",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Knor Tomato Soup",
    ProductID: "E0703",
    Category: "Snacks & Instant Foods",
    SubCategory: "Ready to Eat",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "178",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Acto Popcorn Classic Salted",
    ProductID: "E0704",
    Category: "Snacks & Instant Foods",
    SubCategory: "Ready to Eat",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "179",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Cadbury Silk",
    ProductID: "E0801",
    Category: "Snacks & Instant Foods",
    SubCategory: "Choclates & Candies",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "180",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Cadbury Oreo Silk",
    ProductID: "E0802",
    Category: "Snacks & Instant Foods",
    SubCategory: "Choclates & Candies",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "181",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Bournville",
    ProductID: "E0803",
    Category: "Snacks & Instant Foods",
    SubCategory: "Choclates & Candies",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "182",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Snickers",
    ProductID: "E0804",
    Category: "Snacks & Instant Foods",
    SubCategory: "Choclates & Candies",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "183",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Mango Bite",
    ProductID: "E0805",
    Category: "Snacks & Instant Foods",
    SubCategory: "Choclates & Candies",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "184",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Mothers Mix Pickle",
    ProductID: "E0901",
    Category: "Snacks & Instant Foods",
    SubCategory: "Pickles",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "185",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Mothers Mango Pickle",
    ProductID: "E0902",
    Category: "Snacks & Instant Foods",
    SubCategory: "Pickles",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "186",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Mothers Green Mirch Pickle",
    ProductID: "E0903",
    Category: "Snacks & Instant Foods",
    SubCategory: "Pickles",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "187",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Colgate Max Fresh Gel",
    ProductID: "F0101",
    Category: "Beauty & Hygiene",
    SubCategory: "Oral Care",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "150",
    Price: "188",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Colgate Ultra While Paste",
    ProductID: "F0102",
    Category: "Beauty & Hygiene",
    SubCategory: "Oral Care",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "150",
    Price: "189",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Dabur Red Toothpaste",
    ProductID: "F0103",
    Category: "Beauty & Hygiene",
    SubCategory: "Oral Care",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "150",
    Price: "190",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "CloseUp Max Fresh Gel",
    ProductID: "F0104",
    Category: "Beauty & Hygiene",
    SubCategory: "Oral Care",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "150",
    Price: "191",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Listrine Mouthwash",
    ProductID: "F0105",
    Category: "Beauty & Hygiene",
    SubCategory: "Oral Care",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "150",
    Price: "192",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Wisper Ultra Clean Sanitary Pads",
    ProductID: "F0201",
    Category: "Beauty & Hygiene",
    SubCategory: "Feminine Hygiene",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "150",
    Price: "193",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Stayfree Secure Cottany Soft Pads",
    ProductID: "F0202",
    Category: "Beauty & Hygiene",
    SubCategory: "Feminine Hygiene",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "150",
    Price: "194",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Veet Lotus Hair Remover",
    ProductID: "F0203",
    Category: "Beauty & Hygiene",
    SubCategory: "Feminine Hygiene",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "150",
    Price: "195",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Veet Ultra Wax Strips",
    ProductID: "F0204",
    Category: "Beauty & Hygiene",
    SubCategory: "Feminine Hygiene",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "150",
    Price: "196",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Durex Extra Time Condom",
    ProductID: "F0301",
    Category: "Beauty & Hygiene",
    SubCategory: "Health & Medicine",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "150",
    Price: "197",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "O'range Cotton Earbuds",
    ProductID: "F0302",
    Category: "Beauty & Hygiene",
    SubCategory: "Health & Medicine",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "150",
    Price: "198",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Durex Extra Thin Condom",
    ProductID: "F0303",
    Category: "Beauty & Hygiene",
    SubCategory: "Health & Medicine",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "150",
    Price: "199",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Durex Extra Dotted Condom",
    ProductID: "F0304",
    Category: "Beauty & Hygiene",
    SubCategory: "Health & Medicine",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "150",
    Price: "200",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Dettol Original Handwash",
    ProductID: "F0401",
    Category: "Beauty & Hygiene",
    SubCategory: "Bath & Hand Wash",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "150",
    Price: "201",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Cinthol Fresh Lime Soap",
    ProductID: "F0402",
    Category: "Beauty & Hygiene",
    SubCategory: "Bath & Hand Wash",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "150",
    Price: "202",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Pears Pure & Gentle Wash",
    ProductID: "F0403",
    Category: "Beauty & Hygiene",
    SubCategory: "Bath & Hand Wash",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "150",
    Price: "203",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Nivea Mens Active Bath Gel",
    ProductID: "F0404",
    Category: "Beauty & Hygiene",
    SubCategory: "Bath & Hand Wash",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "150",
    Price: "204",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Pantene Hair Shampoo",
    ProductID: "F0501",
    Category: "Beauty & Hygiene",
    SubCategory: "Hair Care",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "150",
    Price: "205",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Tresmme Extra Smooth Shampoo",
    ProductID: "F0502",
    Category: "Beauty & Hygiene",
    SubCategory: "Hair Care",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "150",
    Price: "206",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Parachute Coconut Oil",
    ProductID: "F0503",
    Category: "Beauty & Hygiene",
    SubCategory: "Hair Care",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "150",
    Price: "207",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Gilette Mach 3 Razor",
    ProductID: "F0601",
    Category: "Beauty & Hygiene",
    SubCategory: "Men's Grooming",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "150",
    Price: "208",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Gilette Regular Shaving Foam",
    ProductID: "F0602",
    Category: "Beauty & Hygiene",
    SubCategory: "Men's Grooming",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "150",
    Price: "209",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Dettole Fresh Shaving Cream",
    ProductID: "F0603",
    Category: "Beauty & Hygiene",
    SubCategory: "Men's Grooming",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "150",
    Price: "210",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Fair & Lovely Beauty Cream",
    ProductID: "F0701",
    Category: "Beauty & Hygiene",
    SubCategory: "Skin Care",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "150",
    Price: "211",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Nivea Face Cream",
    ProductID: "F0702",
    Category: "Beauty & Hygiene",
    SubCategory: "Skin Care",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "150",
    Price: "212",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Ponds White Beauty Cream",
    ProductID: "F0703",
    Category: "Beauty & Hygiene",
    SubCategory: "Skin Care",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "150",
    Price: "213",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Dabur Rose Water",
    ProductID: "F0704",
    Category: "Beauty & Hygiene",
    SubCategory: "Skin Care",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "150",
    Price: "214",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Nivea Cherry Lip Balm",
    ProductID: "F0801",
    Category: "Beauty & Hygiene",
    SubCategory: "Makeup",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "150",
    Price: "215",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Vega Hair Brush",
    ProductID: "F0802",
    Category: "Beauty & Hygiene",
    SubCategory: "Makeup",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "150",
    Price: "216",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Lakme Lipstick",
    ProductID: "F0803",
    Category: "Beauty & Hygiene",
    SubCategory: "Makeup",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "150",
    Price: "217",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Nykaa Nail Paint",
    ProductID: "F0804",
    Category: "Beauty & Hygiene",
    SubCategory: "Makeup",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "150",
    Price: "218",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Axe Chocolate Deodrant",
    ProductID: "F0901",
    Category: "Beauty & Hygiene",
    SubCategory: "Fragrances & Deos",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "150",
    Price: "219",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Kamasutra Deodrant",
    ProductID: "F0902",
    Category: "Beauty & Hygiene",
    SubCategory: "Fragrances & Deos",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "150",
    Price: "220",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Nivea Deodrant",
    ProductID: "F0903",
    Category: "Beauty & Hygiene",
    SubCategory: "Fragrances & Deos",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "150",
    Price: "221",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Axe Refresh Body Spray",
    ProductID: "F0904",
    Category: "Beauty & Hygiene",
    SubCategory: "Fragrances & Deos",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "150",
    Price: "222",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Ariel Matic Liquid Detergent",
    ProductID: "G0101",
    Category: "Cleaning & Household",
    SubCategory: "Detergents & Dishwash",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "223",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Comfort After Wash",
    ProductID: "G0102",
    Category: "Cleaning & Household",
    SubCategory: "Detergents & Dishwash",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "224",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Vim Lemon Dishwash Gel",
    ProductID: "G0103",
    Category: "Cleaning & Household",
    SubCategory: "Detergents & Dishwash",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "225",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Tide Powder Detergent",
    ProductID: "G0104",
    Category: "Cleaning & Household",
    SubCategory: "Detergents & Dishwash",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "226",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Colin Shine Glass Cleaner",
    ProductID: "G0201",
    Category: "Cleaning & Household",
    SubCategory: "All Purpose Cleaners",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "227",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Harpic Power Plus Toilet Cleaner",
    ProductID: "G0202",
    Category: "Cleaning & Household",
    SubCategory: "All Purpose Cleaners",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "228",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Lizol Citrus Floor Cleaner",
    ProductID: "G0203",
    Category: "Cleaning & Household",
    SubCategory: "All Purpose Cleaners",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "229",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Gainda White Phenyl",
    ProductID: "G0204",
    Category: "Cleaning & Household",
    SubCategory: "All Purpose Cleaners",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "230",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Harpic Flushmatic Pine Toilet Block",
    ProductID: "G0205",
    Category: "Cleaning & Household",
    SubCategory: "All Purpose Cleaners",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "231",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Apsara Extra Dark Pencil",
    ProductID: "G0301",
    Category: "Cleaning & Household",
    SubCategory: "Stationary",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "232",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Nataraj Pencil",
    ProductID: "G0302",
    Category: "Cleaning & Household",
    SubCategory: "Stationary",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "233",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Parker Fountain Pen",
    ProductID: "G0303",
    Category: "Cleaning & Household",
    SubCategory: "Stationary",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "234",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Pilot Ball Pen",
    ProductID: "G0304",
    Category: "Cleaning & Household",
    SubCategory: "Stationary",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "235",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Happy Home Toilet Paper",
    ProductID: "G0401",
    Category: "Cleaning & Household",
    SubCategory: "Disposables & Garbage Bags",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "236",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Happy Home Tissue Paper",
    ProductID: "G0402",
    Category: "Cleaning & Household",
    SubCategory: "Disposables & Garbage Bags",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "237",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Happy Home Aluminium Foil",
    ProductID: "G0403",
    Category: "Cleaning & Household",
    SubCategory: "Disposables & Garbage Bags",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "238",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Nature Biodegrad Oxo Garbage Bags",
    ProductID: "G0404",
    Category: "Cleaning & Household",
    SubCategory: "Disposables & Garbage Bags",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "239",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Good Night Power Active Mosquito",
    ProductID: "G0501",
    Category: "Cleaning & Household",
    SubCategory: "Freshness & Repellents",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "240",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "SaveMore Naphthalene Balls",
    ProductID: "G0502",
    Category: "Cleaning & Household",
    SubCategory: "Freshness & Repellents",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "241",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Hit Red CockRoach Killer",
    ProductID: "G0503",
    Category: "Cleaning & Household",
    SubCategory: "Freshness & Repellents",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "242",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Godrej Aer Pocket Car Freshner",
    ProductID: "G0504",
    Category: "Cleaning & Household",
    SubCategory: "Freshness & Repellents",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "243",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Godrej Aer Pocket Bathroom Freshner",
    ProductID: "G0505",
    Category: "Cleaning & Household",
    SubCategory: "Freshness & Repellents",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "244",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Scotch Brite Scrub Pad",
    ProductID: "G0601",
    Category: "Cleaning & Household",
    SubCategory: "Mops, Brushes & Cleaners",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "245",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Scotch Brite Floor Mop",
    ProductID: "G0602",
    Category: "Cleaning & Household",
    SubCategory: "Mops, Brushes & Cleaners",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "246",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Scotch Brite Aluminum Scrub Pad",
    ProductID: "G0603",
    Category: "Cleaning & Household",
    SubCategory: "Mops, Brushes & Cleaners",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "247",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Cherry Blossom Black Shoe Polish",
    ProductID: "G0701",
    Category: "Cleaning & Household",
    SubCategory: "Shoe care",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "248",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Kiwi Black Paste Shoe Polish",
    ProductID: "G0702",
    Category: "Cleaning & Household",
    SubCategory: "Shoe care",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "249",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Cherry Blossom Brown Shoe Polish",
    ProductID: "G0703",
    Category: "Cleaning & Household",
    SubCategory: "Shoe care",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "250",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Cherry Blossom Black  Liquid Shoe Polish",
    ProductID: "G0704",
    Category: "Cleaning & Household",
    SubCategory: "Shoe care",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "251",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Mangaldeep Delux Dhoop Batti",
    ProductID: "G0801",
    Category: "Cleaning & Household",
    SubCategory: "Pooja Essentials",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "252",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Mangaldeep Hawan Samagri",
    ProductID: "G0802",
    Category: "Cleaning & Household",
    SubCategory: "Pooja Essentials",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "253",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Mangaldeep Cotton Diya Baati",
    ProductID: "G0803",
    Category: "Cleaning & Household",
    SubCategory: "Pooja Essentials",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "254",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  },
  {
    OtherStartups: "",
    ProductName: "Mangaldeep Chandan Incense Sticks",
    ProductID: "G0804",
    Category: "Cleaning & Household",
    SubCategory: "Pooja Essentials",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "255",
    Limit: "4",
    Trending: "",
    "": "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: ""
  }
];
