exports.Products = [
  {
    ProductName: "",
    ProductID: "",
    Category: "",
    SubCategory: "",
    SubSubCategory: "",
    Unit: "",
    Breakqty: "",
    Price: "",
    MRP: "",
    Limit: "",
    Trending: "",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Onion",
    ProductID: "A0101",
    Category: "Vegetables & Fruits",
    SubCategory: "Fresh Vegetables",
    SubSubCategory: "",
    Unit: "KG",
    Breakqty: "1",
    Price: "25",
    MRP: "31",
    Limit: "4",
    Trending: "0",
    field12: "",
    Grofers: "",
    Bigbasket: "35",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Potato",
    ProductID: "A0102",
    Category: "Vegetables & Fruits",
    SubCategory: "Fresh Vegetables",
    SubSubCategory: "",
    Unit: "KG",
    Breakqty: "1",
    Price: "30",
    MRP: "37",
    Limit: "4",
    Trending: "0",
    field12: "",
    Grofers: "",
    Bigbasket: "32",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Cauliflower",
    ProductID: "A0103",
    Category: "Vegetables & Fruits",
    SubCategory: "Fresh Vegetables",
    SubSubCategory: "",
    Unit: "PCS",
    Breakqty: "1",
    Price: "20",
    MRP: "25",
    Limit: "4",
    Trending: "1",
    field12: "",
    Grofers: "",
    Bigbasket: "22",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Tomato-Hybrid",
    ProductID: "A0104",
    Category: "Vegetables & Fruits",
    SubCategory: "Fresh Vegetables",
    SubSubCategory: "",
    Unit: "KG",
    Breakqty: "1",
    Price: "12",
    MRP: "15",
    Limit: "4",
    Trending: "1",
    field12: "",
    Grofers: "",
    Bigbasket: "32",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Tomato-Desi",
    ProductID: "A0105",
    Category: "Vegetables & Fruits",
    SubCategory: "Fresh Vegetables",
    SubSubCategory: "",
    Unit: "KG",
    Breakqty: "1",
    Price: "14",
    MRP: "18",
    Limit: "4",
    Trending: "0",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Ladies Finger",
    ProductID: "A0106",
    Category: "Vegetables & Fruits",
    SubCategory: "Fresh Vegetables",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "500",
    Price: "20",
    MRP: "25",
    Limit: "4",
    Trending: "1",
    field12: "",
    Grofers: "",
    Bigbasket: "45",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Capsicum-Green",
    ProductID: "A0107",
    Category: "Vegetables & Fruits",
    SubCategory: "Fresh Vegetables",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "500",
    Price: "15",
    MRP: "19",
    Limit: "4",
    Trending: "1",
    field12: "",
    Grofers: "",
    Bigbasket: "30",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Spinach",
    ProductID: "A0108",
    Category: "Vegetables & Fruits",
    SubCategory: "Fresh Vegetables",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "20",
    MRP: "25",
    Limit: "4",
    Trending: "1",
    field12: "",
    Grofers: "",
    Bigbasket: "20",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Cucumber- Desi",
    ProductID: "A0109",
    Category: "Vegetables & Fruits",
    SubCategory: "Fresh Vegetables",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "500",
    Price: "13",
    MRP: "17",
    Limit: "4",
    Trending: "1",
    field12: "",
    Grofers: "",
    Bigbasket: "8",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Bottle Gourd",
    ProductID: "A0110",
    Category: "Vegetables & Fruits",
    SubCategory: "Fresh Vegetables",
    SubSubCategory: "",
    Unit: "KG",
    Breakqty: "1",
    Price: "28",
    MRP: "35",
    Limit: "4",
    Trending: "1",
    field12: "",
    Grofers: "",
    Bigbasket: "18",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Cabbage",
    ProductID: "A0111",
    Category: "Vegetables & Fruits",
    SubCategory: "Fresh Vegetables",
    SubSubCategory: "",
    Unit: "PCS",
    Breakqty: "1",
    Price: "15",
    MRP: "19",
    Limit: "4",
    Trending: "1",
    field12: "",
    Grofers: "",
    Bigbasket: "15",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Beetroot",
    ProductID: "A0112",
    Category: "Vegetables & Fruits",
    SubCategory: "Fresh Vegetables",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "10",
    MRP: "13",
    Limit: "4",
    Trending: "0",
    field12: "",
    Grofers: "",
    Bigbasket: "12",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Bitter Gourd",
    ProductID: "A0113",
    Category: "Vegetables & Fruits",
    SubCategory: "Fresh Vegetables",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "500",
    Price: "30",
    MRP: "38",
    Limit: "4",
    Trending: "0",
    field12: "",
    Grofers: "",
    Bigbasket: "18",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Colocasia",
    ProductID: "A0114",
    Category: "Vegetables & Fruits",
    SubCategory: "Fresh Vegetables",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "29",
    MRP: "39",
    Limit: "4",
    Trending: "0",
    field12: "",
    Grofers: "",
    Bigbasket: "50",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Brinjal- Purple Bharta",
    ProductID: "A0115",
    Category: "Vegetables & Fruits",
    SubCategory: "Fresh Vegetables",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "500",
    Price: "23",
    MRP: "29",
    Limit: "4",
    Trending: "0",
    field12: "",
    Grofers: "",
    Bigbasket: "25",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Pumpkin-Red",
    ProductID: "A0116",
    Category: "Vegetables & Fruits",
    SubCategory: "Fresh Vegetables",
    SubSubCategory: "",
    Unit: "KG",
    Breakqty: "1",
    Price: "43",
    MRP: "54",
    Limit: "4",
    Trending: "1",
    field12: "",
    Grofers: "",
    Bigbasket: "43",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Carrot-Orange",
    ProductID: "A0117",
    Category: "Vegetables & Fruits",
    SubCategory: "Fresh Vegetables",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "500",
    Price: "15",
    MRP: "19",
    Limit: "4",
    Trending: "0",
    field12: "",
    Grofers: "",
    Bigbasket: "NA",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Parwal",
    ProductID: "A0118",
    Category: "Vegetables & Fruits",
    SubCategory: "Fresh Vegetables",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "26",
    MRP: "33",
    Limit: "4",
    Trending: "1",
    field12: "",
    Grofers: "",
    Bigbasket: "46",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Sponge Gourd",
    ProductID: "A0119",
    Category: "Vegetables & Fruits",
    SubCategory: "Fresh Vegetables",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "500",
    Price: "30",
    MRP: "38",
    Limit: "4",
    Trending: "0",
    field12: "",
    Grofers: "",
    Bigbasket: "42",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Kakdi",
    ProductID: "A0120",
    Category: "Vegetables & Fruits",
    SubCategory: "Fresh Vegetables",
    SubSubCategory: "",
    Unit: "KG",
    Breakqty: "1",
    Price: "20",
    MRP: "25",
    Limit: "4",
    Trending: "0",
    field12: "",
    Grofers: "",
    Bigbasket: "35",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Green Peas",
    ProductID: "A0121",
    Category: "Vegetables & Fruits",
    SubCategory: "Fresh Vegetables",
    SubSubCategory: "",
    Unit: "KG",
    Breakqty: "1",
    Price: "72",
    MRP: "90",
    Limit: "4",
    Trending: "1",
    field12: "",
    Grofers: "",
    Bigbasket: "96",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Beans- Broad",
    ProductID: "A0122",
    Category: "Vegetables & Fruits",
    SubCategory: "Fresh Vegetables",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "500",
    Price: "52",
    MRP: "65",
    Limit: "4",
    Trending: "0",
    field12: "",
    Grofers: "",
    Bigbasket: "34",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Brinjal- Purple Long",
    ProductID: "A0123",
    Category: "Vegetables & Fruits",
    SubCategory: "Fresh Vegetables",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "500",
    Price: "21",
    MRP: "26",
    Limit: "4",
    Trending: "1",
    field12: "",
    Grofers: "",
    Bigbasket: "29",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Beans-French, Round",
    ProductID: "A0124",
    Category: "Vegetables & Fruits",
    SubCategory: "Fresh Vegetables",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "500",
    Price: "52",
    MRP: "65",
    Limit: "4",
    Trending: "1",
    field12: "",
    Grofers: "",
    Bigbasket: "31",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Pumpkin-Disco",
    ProductID: "A0125",
    Category: "Vegetables & Fruits",
    SubCategory: "Fresh Vegetables",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "500",
    Price: "6",
    MRP: "8",
    Limit: "4",
    Trending: "0",
    field12: "",
    Grofers: "",
    Bigbasket: "10",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Ginger",
    ProductID: "A0201",
    Category: "Vegetables & Fruits",
    SubCategory: "Herbs & Seasonings",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "40",
    MRP: "50",
    Limit: "4",
    Trending: "1",
    field12: "",
    Grofers: "",
    Bigbasket: "42",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Lemon",
    ProductID: "A0202",
    Category: "Vegetables & Fruits",
    SubCategory: "Herbs & Seasonings",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "24",
    MRP: "30",
    Limit: "4",
    Trending: "1",
    field12: "",
    Grofers: "",
    Bigbasket: "37.5",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Garlic",
    ProductID: "A0203",
    Category: "Vegetables & Fruits",
    SubCategory: "Herbs & Seasonings",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "40",
    MRP: "50",
    Limit: "4",
    Trending: "0",
    field12: "",
    Grofers: "",
    Bigbasket: "50",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Chilli-Green",
    ProductID: "A0204",
    Category: "Vegetables & Fruits",
    SubCategory: "Herbs & Seasonings",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "11",
    MRP: "14",
    Limit: "4",
    Trending: "0",
    field12: "",
    Grofers: "",
    Bigbasket: "25",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Corriander Leaves",
    ProductID: "A0205",
    Category: "Vegetables & Fruits",
    SubCategory: "Herbs & Seasonings",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "18",
    MRP: "23",
    Limit: "4",
    Trending: "1",
    field12: "",
    Grofers: "",
    Bigbasket: "13",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Mint Leaves",
    ProductID: "A0206",
    Category: "Vegetables & Fruits",
    SubCategory: "Herbs & Seasonings",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "19",
    MRP: "24",
    Limit: "4",
    Trending: "1",
    field12: "",
    Grofers: "",
    Bigbasket: "27",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Broccoli",
    ProductID: "A0301",
    Category: "Vegetables & Fruits",
    SubCategory: "Exotic Vegetables",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "500",
    Price: "69",
    MRP: "86",
    Limit: "4",
    Trending: "0",
    field12: "",
    Grofers: "",
    Bigbasket: "56",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Spring Onion",
    ProductID: "A0302",
    Category: "Vegetables & Fruits",
    SubCategory: "Exotic Vegetables",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "500",
    Price: "21",
    MRP: "26",
    Limit: "4",
    Trending: "1",
    field12: "",
    Grofers: "",
    Bigbasket: "23",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Cumumber-English",
    ProductID: "A0303",
    Category: "Vegetables & Fruits",
    SubCategory: "Exotic Vegetables",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "500",
    Price: "16",
    MRP: "20",
    Limit: "4",
    Trending: "1",
    field12: "",
    Grofers: "",
    Bigbasket: "19",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Capsicum-Yellow",
    ProductID: "A0304",
    Category: "Vegetables & Fruits",
    SubCategory: "Exotic Vegetables",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "",
    MRP: "",
    Limit: "4",
    Trending: "1",
    field12: "",
    Grofers: "",
    Bigbasket: "25",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Lettuce",
    ProductID: "A0305",
    Category: "Vegetables & Fruits",
    SubCategory: "Exotic Vegetables",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "49",
    MRP: "149",
    Limit: "4",
    Trending: "1",
    field12: "",
    Grofers: "",
    Bigbasket: "25",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Sweet Corn",
    ProductID: "A0306",
    Category: "Vegetables & Fruits",
    SubCategory: "Exotic Vegetables",
    SubSubCategory: "",
    Unit: "PCS",
    Breakqty: "1",
    Price: "",
    MRP: "",
    Limit: "4",
    Trending: "1",
    field12: "",
    Grofers: "",
    Bigbasket: "23.5",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Zucchini- Yellow",
    ProductID: "A0307",
    Category: "Vegetables & Fruits",
    SubCategory: "Exotic Vegetables",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "500",
    Price: "43",
    MRP: "54",
    Limit: "4",
    Trending: "1",
    field12: "",
    Grofers: "",
    Bigbasket: "38",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Mushroom- White Button",
    ProductID: "A0308",
    Category: "Vegetables & Fruits",
    SubCategory: "Exotic Vegetables",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "200",
    Price: "50",
    MRP: "63",
    Limit: "4",
    Trending: "0",
    field12: "",
    Grofers: "",
    Bigbasket: "NA",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Zucchini- Green",
    ProductID: "A0309",
    Category: "Vegetables & Fruits",
    SubCategory: "Exotic Vegetables",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "500",
    Price: "38",
    MRP: "48",
    Limit: "4",
    Trending: "0",
    field12: "",
    Grofers: "",
    Bigbasket: "35",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Capsicum-Red",
    ProductID: "A0310",
    Category: "Vegetables & Fruits",
    SubCategory: "Exotic Vegetables",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "",
    MRP: "",
    Limit: "4",
    Trending: "0",
    field12: "",
    Grofers: "",
    Bigbasket: "25",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Banana",
    ProductID: "A0401",
    Category: "Vegetables & Fruits",
    SubCategory: "Fresh Fruits",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "500",
    Price: "29",
    MRP: "36",
    Limit: "4",
    Trending: "0",
    field12: "",
    Grofers: "",
    Bigbasket: "57/kg",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Grapes-Green Seedless",
    ProductID: "A0402",
    Category: "Vegetables & Fruits",
    SubCategory: "Fresh Fruits",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "500",
    Price: "70",
    MRP: "88",
    Limit: "4",
    Trending: "1",
    field12: "",
    Grofers: "",
    Bigbasket: "70",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Pomegranate",
    ProductID: "A0403",
    Category: "Vegetables & Fruits",
    SubCategory: "Fresh Fruits",
    SubSubCategory: "",
    Unit: "PCS",
    Breakqty: "4",
    Price: "135",
    MRP: "169",
    Limit: "4",
    Trending: "0",
    field12: "",
    Grofers: "",
    Bigbasket: "149",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Orange- Nagpur,Regular",
    ProductID: "A0404",
    Category: "Vegetables & Fruits",
    SubCategory: "Fresh Fruits",
    SubSubCategory: "",
    Unit: "KG",
    Breakqty: "1",
    Price: "",
    MRP: "",
    Limit: "4",
    Trending: "1",
    field12: "",
    Grofers: "",
    Bigbasket: "79",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Apple- Red Delicious, Washington",
    ProductID: "A0405",
    Category: "Vegetables & Fruits",
    SubCategory: "Fresh Fruits",
    SubSubCategory: "",
    Unit: "PCS",
    Breakqty: "4",
    Price: "120",
    MRP: "150",
    Limit: "4",
    Trending: "0",
    field12: "",
    Grofers: "",
    Bigbasket: "165",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Papaya",
    ProductID: "A0406",
    Category: "Vegetables & Fruits",
    SubCategory: "Fresh Fruits",
    SubSubCategory: "",
    Unit: "PCS",
    Breakqty: "1",
    Price: "",
    MRP: "",
    Limit: "4",
    Trending: "0",
    field12: "",
    Grofers: "",
    Bigbasket: "80",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Apple- Shimla",
    ProductID: "A0407",
    Category: "Vegetables & Fruits",
    SubCategory: "Fresh Fruits",
    SubSubCategory: "",
    Unit: "PCS",
    Breakqty: "4",
    Price: "108",
    MRP: "135",
    Limit: "4",
    Trending: "1",
    field12: "",
    Grofers: "",
    Bigbasket: "99",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Grapes-Black Seedless",
    ProductID: "A0408",
    Category: "Vegetables & Fruits",
    SubCategory: "Fresh Fruits",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "500",
    Price: "",
    MRP: "",
    Limit: "4",
    Trending: "0",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Apple- Royal Gala",
    ProductID: "A0409",
    Category: "Vegetables & Fruits",
    SubCategory: "Fresh Fruits",
    SubSubCategory: "",
    Unit: "PCS",
    Breakqty: "4",
    Price: "145",
    MRP: "181",
    Limit: "4",
    Trending: "1",
    field12: "",
    Grofers: "",
    Bigbasket: "165",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Gauva",
    ProductID: "A0410",
    Category: "Vegetables & Fruits",
    SubCategory: "Fresh Fruits",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "500",
    Price: "",
    MRP: "",
    Limit: "4",
    Trending: "1",
    field12: "",
    Grofers: "",
    Bigbasket: "NA",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Mango-Safeda",
    ProductID: "A0411",
    Category: "Vegetables & Fruits",
    SubCategory: "Fresh Fruits",
    SubSubCategory: "",
    Unit: "KG",
    Breakqty: "1",
    Price: "109",
    MRP: "136",
    Limit: "4",
    Trending: "0",
    field12: "",
    Grofers: "",
    Bigbasket: "119",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Watermelon",
    ProductID: "A0412",
    Category: "Vegetables & Fruits",
    SubCategory: "Fresh Fruits",
    SubSubCategory: "",
    Unit: "PCS",
    Breakqty: "1",
    Price: "39",
    MRP: "49",
    Limit: "4",
    Trending: "1",
    field12: "",
    Grofers: "",
    Bigbasket: "55",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Coconut",
    ProductID: "A0413",
    Category: "Vegetables & Fruits",
    SubCategory: "Fresh Fruits",
    SubSubCategory: "",
    Unit: "PCS",
    Breakqty: "1",
    Price: "",
    MRP: "",
    Limit: "4",
    Trending: "1",
    field12: "",
    Grofers: "",
    Bigbasket: "42",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Pineapple",
    ProductID: "A0414",
    Category: "Vegetables & Fruits",
    SubCategory: "Fresh Fruits",
    SubSubCategory: "",
    Unit: "PCS",
    Breakqty: "1",
    Price: "",
    MRP: "0",
    Limit: "4",
    Trending: "0",
    field12: "",
    Grofers: "",
    Bigbasket: "58",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Apple-Fuji",
    ProductID: "A0415",
    Category: "Vegetables & Fruits",
    SubCategory: "Fresh Fruits",
    SubSubCategory: "",
    Unit: "PCS",
    Breakqty: "4",
    Price: "114",
    MRP: "143",
    Limit: "4",
    Trending: "0",
    field12: "",
    Grofers: "",
    Bigbasket: "189",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Kiwi-Green",
    ProductID: "A0501",
    Category: "Vegetables & Fruits",
    SubCategory: "Exotic Fruits",
    SubSubCategory: "",
    Unit: "PCS",
    Breakqty: "3",
    Price: "69",
    MRP: "86",
    Limit: "4",
    Trending: "1",
    field12: "",
    Grofers: "",
    Bigbasket: "119",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Grapes-Red Globe",
    ProductID: "A0502",
    Category: "Vegetables & Fruits",
    SubCategory: "Exotic Fruits",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "",
    MRP: "",
    Limit: "4",
    Trending: "1",
    field12: "",
    Grofers: "",
    Bigbasket: "130",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Strawberry",
    ProductID: "A0503",
    Category: "Vegetables & Fruits",
    SubCategory: "Exotic Fruits",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "",
    MRP: "",
    Limit: "4",
    Trending: "0",
    field12: "",
    Grofers: "",
    Bigbasket: "NA",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Tender Coconut",
    ProductID: "A0504",
    Category: "Vegetables & Fruits",
    SubCategory: "Exotic Fruits",
    SubSubCategory: "",
    Unit: "PCS",
    Breakqty: "1",
    Price: "45",
    MRP: "56",
    Limit: "4",
    Trending: "1",
    field12: "",
    Grofers: "",
    Bigbasket: "49",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Pears",
    ProductID: "A0505",
    Category: "Vegetables & Fruits",
    SubCategory: "Exotic Fruits",
    SubSubCategory: "",
    Unit: "PCS",
    Breakqty: "4",
    Price: "105",
    MRP: "131",
    Limit: "4",
    Trending: "1",
    field12: "",
    Grofers: "",
    Bigbasket: "199",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Muskmelon",
    ProductID: "A0506",
    Category: "Vegetables & Fruits",
    SubCategory: "Exotic Fruits",
    SubSubCategory: "",
    Unit: "PCS",
    Breakqty: "1",
    Price: "79",
    MRP: "99",
    Limit: "4",
    Trending: "1",
    field12: "",
    Grofers: "",
    Bigbasket: "69",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Aashirvaad Atta- Whole Wheat",
    ProductID: "B0101",
    Category: "Food Grains, Oil & Masala",
    SubCategory: "Atta, Flour & Sooji",
    SubSubCategory: "",
    Unit: "KG",
    Breakqty: "10",
    Price: "373",
    MRP: "375",
    Limit: "4",
    Trending: "1",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Rajdhani Sooji, Rava",
    ProductID: "B0102",
    Category: "Food Grains, Oil & Masala",
    SubCategory: "Atta, Flour & Sooji",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "500",
    Price: "38",
    MRP: "41",
    Limit: "4",
    Trending: "1",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Rajdhani Besan",
    ProductID: "B0103",
    Category: "Food Grains, Oil & Masala",
    SubCategory: "Atta, Flour & Sooji",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "500",
    Price: "50",
    MRP: "60",
    Limit: "4",
    Trending: "1",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Rajhani Chana Sattu",
    ProductID: "B0104",
    Category: "Food Grains, Oil & Masala",
    SubCategory: "Atta, Flour & Sooji",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "500",
    Price: "42",
    MRP: "46",
    Limit: "4",
    Trending: "0",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Patanjali Atta- Whole Wheat",
    ProductID: "B0105",
    Category: "Food Grains, Oil & Masala",
    SubCategory: "Atta, Flour & Sooji",
    SubSubCategory: "",
    Unit: "KG",
    Breakqty: "10",
    Price: "347",
    MRP: "360",
    Limit: "4",
    Trending: "0",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Rajdhani Arhar Daal, Toor Daal",
    ProductID: "B0201",
    Category: "Food Grains, Oil & Masala",
    SubCategory: "Dals & Pulses",
    SubSubCategory: "",
    Unit: "KG",
    Breakqty: "1",
    Price: "111",
    MRP: "120",
    Limit: "4",
    Trending: "0",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Rajdhani Urad Daal (Chilka)",
    ProductID: "B0202",
    Category: "Food Grains, Oil & Masala",
    SubCategory: "Dals & Pulses",
    SubSubCategory: "",
    Unit: "KG",
    Breakqty: "1",
    Price: "142",
    MRP: "180",
    Limit: "4",
    Trending: "0",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Rajdhani Moong Dal (Dhuli)",
    ProductID: "B0203",
    Category: "Food Grains, Oil & Masala",
    SubCategory: "Dals & Pulses",
    SubSubCategory: "",
    Unit: "KG",
    Breakqty: "1",
    Price: "138",
    MRP: "140",
    Limit: "4",
    Trending: "1",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Rajdhani Rajma",
    ProductID: "B0204",
    Category: "Food Grains, Oil & Masala",
    SubCategory: "Dals & Pulses",
    SubSubCategory: "",
    Unit: "KG",
    Breakqty: "1",
    Price: "107",
    MRP: "140",
    Limit: "4",
    Trending: "0",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Rajdhani Kabuli Chana",
    ProductID: "B0205",
    Category: "Food Grains, Oil & Masala",
    SubCategory: "Dals & Pulses",
    SubSubCategory: "",
    Unit: "KG",
    Breakqty: "1",
    Price: "101",
    MRP: "125",
    Limit: "4",
    Trending: "1",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Daawat Basmati Rice- Super",
    ProductID: "B0301",
    Category: "Food Grains, Oil & Masala",
    SubCategory: "Rice & Rice Products",
    SubSubCategory: "",
    Unit: "KG",
    Breakqty: "1",
    Price: "164",
    MRP: "165",
    Limit: "4",
    Trending: "0",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Daawat Basmati Rice- Rozana Gold",
    ProductID: "B0302",
    Category: "Food Grains, Oil & Masala",
    SubCategory: "Rice & Rice Products",
    SubSubCategory: "",
    Unit: "KG",
    Breakqty: "1",
    Price: "97",
    MRP: "99",
    Limit: "4",
    Trending: "0",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "India Gate Basmati Rice- Dubar",
    ProductID: "B0303",
    Category: "Food Grains, Oil & Masala",
    SubCategory: "Rice & Rice Products",
    SubSubCategory: "",
    Unit: "KG",
    Breakqty: "5",
    Price: "513",
    MRP: "610",
    Limit: "4",
    Trending: "1",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "India Gate Basmati Rice- Feast Rozzana",
    ProductID: "B0304",
    Category: "Food Grains, Oil & Masala",
    SubCategory: "Rice & Rice Products",
    SubSubCategory: "",
    Unit: "KG",
    Breakqty: "5",
    Price: "405",
    MRP: "485",
    Limit: "4",
    Trending: "0",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Fortune Soya Health Refined Soyabean Oil (Pouch)",
    ProductID: "B0401",
    Category: "Food Grains, Oil & Masala",
    SubCategory: "Edible Oils, Ghee & Vinegar",
    SubSubCategory: "",
    Unit: "LT",
    Breakqty: "1",
    Price: "119",
    MRP: "130",
    Limit: "4",
    Trending: "1",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Fortune Premium Kachi Ghani Pure Mustard Oil (Bottle)",
    ProductID: "B0402",
    Category: "Food Grains, Oil & Masala",
    SubCategory: "Edible Oils, Ghee & Vinegar",
    SubSubCategory: "",
    Unit: "LT",
    Breakqty: "1",
    Price: "134",
    MRP: "149",
    Limit: "4",
    Trending: "1",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Milkfood Rich Desi Danedar Ghee (Carton)",
    ProductID: "B0403",
    Category: "Food Grains, Oil & Masala",
    SubCategory: "Edible Oils, Ghee & Vinegar",
    SubSubCategory: "",
    Unit: "LT",
    Breakqty: "1",
    Price: "479",
    MRP: "498",
    Limit: "4",
    Trending: "0",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Patanjali Cow Ghee (Carton)",
    ProductID: "B0404",
    Category: "Food Grains, Oil & Masala",
    SubCategory: "Edible Oils, Ghee & Vinegar",
    SubSubCategory: "",
    Unit: "LT",
    Breakqty: "1",
    Price: "565",
    MRP: "565",
    Limit: "4",
    Trending: "1",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Figaro Olive Oil- Pure",
    ProductID: "B0405",
    Category: "Food Grains, Oil & Masala",
    SubCategory: "Edible Oils, Ghee & Vinegar",
    SubSubCategory: "",
    Unit: "LT",
    Breakqty: "1",
    Price: "851",
    MRP: "925",
    Limit: "4",
    Trending: "1",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Catch Tumeric Powder, Haldi",
    ProductID: "B0501",
    Category: "Food Grains, Oil & Masala",
    SubCategory: "Masala & Spices",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "500",
    Price: "121",
    MRP: "135",
    Limit: "4",
    Trending: "0",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Catch Coriander Powder",
    ProductID: "B0502",
    Category: "Food Grains, Oil & Masala",
    SubCategory: "Masala & Spices",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "200",
    Price: "52",
    MRP: "58",
    Limit: "4",
    Trending: "0",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Catch Super Garam Masala",
    ProductID: "B0503",
    Category: "Food Grains, Oil & Masala",
    SubCategory: "Masala & Spices",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "200",
    Price: "63",
    MRP: "70",
    Limit: "4",
    Trending: "1",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Catch Compounded Hing Powder",
    ProductID: "B0504",
    Category: "Food Grains, Oil & Masala",
    SubCategory: "Masala & Spices",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "50",
    Price: "72",
    MRP: "80",
    Limit: "4",
    Trending: "1",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Mawana Premium Crystal Sulphurless Sugar",
    ProductID: "B0601",
    Category: "Food Grains, Oil & Masala",
    SubCategory: "Salt, Sugar & Dry Fruits",
    SubSubCategory: "",
    Unit: "KG",
    Breakqty: "1",
    Price: "59",
    MRP: "65",
    Limit: "4",
    Trending: "0",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Tata Salt",
    ProductID: "B0602",
    Category: "Food Grains, Oil & Masala",
    SubCategory: "Salt, Sugar & Dry Fruits",
    SubSubCategory: "",
    Unit: "KG",
    Breakqty: "1",
    Price: "20",
    MRP: "20",
    Limit: "4",
    Trending: "1",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Pariwar Food Richmond- Raisins",
    ProductID: "B0603",
    Category: "Food Grains, Oil & Masala",
    SubCategory: "Salt, Sugar & Dry Fruits",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "200",
    Price: "147",
    MRP: "160",
    Limit: "4",
    Trending: "1",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Pariwar Food Richmond- Almonds",
    ProductID: "B0604",
    Category: "Food Grains, Oil & Masala",
    SubCategory: "Salt, Sugar & Dry Fruits",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "200",
    Price: "279",
    MRP: "325",
    Limit: "4",
    Trending: "1",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Amul Taaza Toned Milk (Pouch)",
    ProductID: "C0101",
    Category: "Bread & Dairy Products",
    SubCategory: "Dairy Products",
    SubSubCategory: "",
    Unit: "ML",
    Breakqty: "500",
    Price: "23",
    MRP: "23",
    Limit: "4",
    Trending: "1",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Amul Full Cream Milk (Pouch)",
    ProductID: "C0102",
    Category: "Bread & Dairy Products",
    SubCategory: "Dairy Products",
    SubSubCategory: "",
    Unit: "ML",
    Breakqty: "500",
    Price: "28",
    MRP: "28",
    Limit: "4",
    Trending: "1",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Mother Dairy Toned Milk (Pouch)",
    ProductID: "C0103",
    Category: "Bread & Dairy Products",
    SubCategory: "Dairy Products",
    SubSubCategory: "",
    Unit: "ML",
    Breakqty: "500",
    Price: "23",
    MRP: "23",
    Limit: "4",
    Trending: "1",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Mother Dairy Classic Dahi (Pouch)",
    ProductID: "C0104",
    Category: "Bread & Dairy Products",
    SubCategory: "Dairy Products",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "400",
    Price: "30",
    MRP: "30",
    Limit: "4",
    Trending: "0",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Amul Plain Buttermilk Chach (Pouch)",
    ProductID: "C0105",
    Category: "Bread & Dairy Products",
    SubCategory: "Dairy Products",
    SubSubCategory: "",
    Unit: "ML",
    Breakqty: "500",
    Price: "12",
    MRP: "12",
    Limit: "4",
    Trending: "0",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "English Oven Brown Bread",
    ProductID: "C0201",
    Category: "Bread & Dairy Products",
    SubCategory: "Bread & Buns",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "400",
    Price: "35",
    MRP: "35",
    Limit: "4",
    Trending: "0",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Harvest Gold White Bread",
    ProductID: "C0202",
    Category: "Bread & Dairy Products",
    SubCategory: "Bread & Buns",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "350",
    Price: "22",
    MRP: "22",
    Limit: "4",
    Trending: "0",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "English Oven Premium Sandwhich Bread",
    ProductID: "C0203",
    Category: "Bread & Dairy Products",
    SubCategory: "Bread & Buns",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "400",
    Price: "33",
    MRP: "33",
    Limit: "4",
    Trending: "1",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "English Oven Fruit Bun Bread",
    ProductID: "C0204",
    Category: "Bread & Dairy Products",
    SubCategory: "Bread & Buns",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "150",
    Price: "17",
    MRP: "17",
    Limit: "4",
    Trending: "0",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Quaker Oats",
    ProductID: "C0301",
    Category: "Bread & Dairy Products",
    SubCategory: "Cereals & Oats",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "200",
    Price: "42",
    MRP: "42",
    Limit: "4",
    Trending: "1",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Kellogg's Chacos Cereal",
    ProductID: "C0302",
    Category: "Bread & Dairy Products",
    SubCategory: "Cereals & Oats",
    SubSubCategory: "",
    Unit: "KG",
    Breakqty: "1",
    Price: "436",
    MRP: "470",
    Limit: "4",
    Trending: "0",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Kellogg's Original Cornflakes (Pouch)",
    ProductID: "C0303",
    Category: "Bread & Dairy Products",
    SubCategory: "Cereals & Oats",
    SubSubCategory: "",
    Unit: "KG",
    Breakqty: "1",
    Price: "392",
    MRP: "425",
    Limit: "4",
    Trending: "0",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Saffola Classic Masala Oats",
    ProductID: "C0304",
    Category: "Bread & Dairy Products",
    SubCategory: "Cereals & Oats",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "500",
    Price: "175",
    MRP: "190",
    Limit: "4",
    Trending: "1",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Wagh Bakri Premium Tea",
    ProductID: "D0101",
    Category: "Beverages",
    SubCategory: "Tea",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "130",
    MRP: "130",
    Limit: "4",
    Trending: "0",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Tetley Lemon Green Tea",
    ProductID: "D0102",
    Category: "Beverages",
    SubCategory: "Tea",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "500",
    Price: "145",
    MRP: "145",
    Limit: "4",
    Trending: "1",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Tata Premium Tea",
    ProductID: "D0103",
    Category: "Beverages",
    SubCategory: "Tea",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "500",
    Price: "187",
    MRP: "193",
    Limit: "4",
    Trending: "1",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Brooke Bond Tea- Taj Mahal",
    ProductID: "D0104",
    Category: "Beverages",
    SubCategory: "Tea",
    SubSubCategory: "",
    Unit: "KG",
    Breakqty: "1",
    Price: "436",
    MRP: "480",
    Limit: "4",
    Trending: "0",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Brooke Bond Tea- Red Label",
    ProductID: "D0105",
    Category: "Beverages",
    SubCategory: "Tea",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "100",
    MRP: "100",
    Limit: "4",
    Trending: "1",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Nescafe Classic Coffee",
    ProductID: "D0201",
    Category: "Beverages",
    SubCategory: "Coffee",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "50",
    Price: "150",
    MRP: "150",
    Limit: "4",
    Trending: "1",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Bru Gold Coffee",
    ProductID: "D0202",
    Category: "Beverages",
    SubCategory: "Coffee",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "500",
    Price: "",
    MRP: "",
    Limit: "4",
    Trending: "0",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Nescafe Gold Blend Coffee",
    ProductID: "D0203",
    Category: "Beverages",
    SubCategory: "Coffee",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "500",
    Price: "",
    MRP: "",
    Limit: "4",
    Trending: "0",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Thums Up Soft Drink (Bottle)",
    ProductID: "D0301",
    Category: "Beverages",
    SubCategory: "Soft Drinks & Soda",
    SubSubCategory: "",
    Unit: "LT",
    Breakqty: "1",
    Price: "55",
    MRP: "65",
    Limit: "4",
    Trending: "1",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Coco cola Soft Drink (Bottle)",
    ProductID: "D0302",
    Category: "Beverages",
    SubCategory: "Soft Drinks & Soda",
    SubSubCategory: "",
    Unit: "ML",
    Breakqty: "500",
    Price: "",
    MRP: "",
    Limit: "4",
    Trending: "1",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Limca Soft Drink (Bottle)",
    ProductID: "D0303",
    Category: "Beverages",
    SubCategory: "Soft Drinks & Soda",
    SubSubCategory: "",
    Unit: "ML",
    Breakqty: "500",
    Price: "",
    MRP: "",
    Limit: "4",
    Trending: "0",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Pespi Soft Drink (Bottle)",
    ProductID: "D0304",
    Category: "Beverages",
    SubCategory: "Soft Drinks & Soda",
    SubSubCategory: "",
    Unit: "ML",
    Breakqty: "500",
    Price: "",
    MRP: "",
    Limit: "4",
    Trending: "1",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Complan Royale Chocolate (Carton)",
    ProductID: "D0401",
    Category: "Beverages",
    SubCategory: "Health Drinks",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "500",
    Price: "280",
    MRP: "280",
    Limit: "4",
    Trending: "1",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Cadbury Bourn Vita (bottle)",
    ProductID: "D0402",
    Category: "Beverages",
    SubCategory: "Health Drinks",
    SubSubCategory: "",
    Unit: "KG",
    Breakqty: "1",
    Price: "400",
    MRP: "400",
    Limit: "4",
    Trending: "1",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Horlicks Classic Malt (Bottle)",
    ProductID: "D0403",
    Category: "Beverages",
    SubCategory: "Health Drinks",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "400",
    Price: "299",
    MRP: "299",
    Limit: "4",
    Trending: "1",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Glucon-D Orange",
    ProductID: "D0404",
    Category: "Beverages",
    SubCategory: "Health Drinks",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "450",
    Price: "160",
    MRP: "160",
    Limit: "4",
    Trending: "1",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Real Mixed Fruit Juice",
    ProductID: "D0501",
    Category: "Beverages",
    SubCategory: "Fruit Juices & Drinks",
    SubSubCategory: "",
    Unit: "LT",
    Breakqty: "1",
    Price: "90",
    MRP: "105",
    Limit: "4",
    Trending: "1",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Tropicana Orange Juice",
    ProductID: "D0502",
    Category: "Beverages",
    SubCategory: "Fruit Juices & Drinks",
    SubSubCategory: "",
    Unit: "LT",
    Breakqty: "1",
    Price: "90",
    MRP: "110",
    Limit: "4",
    Trending: "0",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Real Mango Juice",
    ProductID: "D0503",
    Category: "Beverages",
    SubCategory: "Fruit Juices & Drinks",
    SubSubCategory: "",
    Unit: "LT",
    Breakqty: "1",
    Price: "85",
    MRP: "100",
    Limit: "4",
    Trending: "0",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Tropicana Litchi Delight Juice",
    ProductID: "D0504",
    Category: "Beverages",
    SubCategory: "Fruit Juices & Drinks",
    SubSubCategory: "",
    Unit: "LT",
    Breakqty: "1",
    Price: "110",
    MRP: "110",
    Limit: "4",
    Trending: "0",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Bisleri Mountain Water",
    ProductID: "D0601",
    Category: "Beverages",
    SubCategory: "Water",
    SubSubCategory: "",
    Unit: "LT",
    Breakqty: "1",
    Price: "20",
    MRP: "20",
    Limit: "4",
    Trending: "0",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Aquafina Water",
    ProductID: "D0602",
    Category: "Beverages",
    SubCategory: "Water",
    SubSubCategory: "",
    Unit: "LT",
    Breakqty: "1",
    Price: "20",
    MRP: "20",
    Limit: "4",
    Trending: "1",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Bailley Water",
    ProductID: "D0603",
    Category: "Beverages",
    SubCategory: "Water",
    SubSubCategory: "",
    Unit: "LT",
    Breakqty: "1",
    Price: "20",
    MRP: "20",
    Limit: "4",
    Trending: "0",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Kinley Water",
    ProductID: "D0604",
    Category: "Beverages",
    SubCategory: "Water",
    SubSubCategory: "",
    Unit: "LT",
    Breakqty: "1",
    Price: "20",
    MRP: "20",
    Limit: "4",
    Trending: "1",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Maggi Masala Noodles",
    ProductID: "E0101",
    Category: "Snacks & Instant Foods",
    SubCategory: "Noodles & Pasta",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "",
    MRP: "",
    Limit: "4",
    Trending: "0",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Sunfeast Yippee Magic Masala Noodles",
    ProductID: "E0102",
    Category: "Snacks & Instant Foods",
    SubCategory: "Noodles & Pasta",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "60",
    Price: "10",
    MRP: "10",
    Limit: "4",
    Trending: "0",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Maggi Masala Atta Noodles",
    ProductID: "E0103",
    Category: "Snacks & Instant Foods",
    SubCategory: "Noodles & Pasta",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "60",
    Price: "",
    MRP: "",
    Limit: "4",
    Trending: "1",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Ching's Hot Garlic Instant Noodles",
    ProductID: "E0104",
    Category: "Snacks & Instant Foods",
    SubCategory: "Noodles & Pasta",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "60",
    Price: "10",
    MRP: "10",
    Limit: "4",
    Trending: "0",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Sunfeast Nice Sugar Sprinkled Biscuits",
    ProductID: "E0301",
    Category: "Snacks & Instant Foods",
    SubCategory: "Biscuits & Cookies",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "",
    MRP: "",
    Limit: "4",
    Trending: "1",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Sunfeast Dark Fantasy Choco Fills",
    ProductID: "E0302",
    Category: "Snacks & Instant Foods",
    SubCategory: "Biscuits & Cookies",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "75",
    Price: "30",
    MRP: "30",
    Limit: "4",
    Trending: "0",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Parle Platina Hide & Seek",
    ProductID: "E0303",
    Category: "Snacks & Instant Foods",
    SubCategory: "Biscuits & Cookies",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "120",
    Price: "30",
    MRP: "30",
    Limit: "4",
    Trending: "0",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Britannia Good Day Cashew Cookies",
    ProductID: "E0304",
    Category: "Snacks & Instant Foods",
    SubCategory: "Biscuits & Cookies",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "",
    MRP: "",
    Limit: "4",
    Trending: "1",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Safal Frozen Green Peas",
    ProductID: "E0401",
    Category: "Snacks & Instant Foods",
    SubCategory: "Frozen Veggies & Snacks",
    SubSubCategory: "",
    Unit: "KG",
    Breakqty: "1",
    Price: "190",
    MRP: "190",
    Limit: "4",
    Trending: "1",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "McCain Smiles Crispy Happy Potatoes",
    ProductID: "E0402",
    Category: "Snacks & Instant Foods",
    SubCategory: "Frozen Veggies & Snacks",
    SubSubCategory: "",
    Unit: "KG",
    Breakqty: "1",
    Price: "290",
    MRP: "290",
    Limit: "4",
    Trending: "0",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "McCain Super Wedges",
    ProductID: "E0403",
    Category: "Snacks & Instant Foods",
    SubCategory: "Frozen Veggies & Snacks",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "400",
    Price: "115",
    MRP: "115",
    Limit: "4",
    Trending: "1",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "McCain Aloo Tikki",
    ProductID: "E0404",
    Category: "Snacks & Instant Foods",
    SubCategory: "Frozen Veggies & Snacks",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "760",
    Price: "160",
    MRP: "160",
    Limit: "4",
    Trending: "1",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Heinz Tomato Ketchup (Bottle)",
    ProductID: "E0501",
    Category: "Snacks & Instant Foods",
    SubCategory: "Spreads, Sauces & Ketchup",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "900",
    Price: "165",
    MRP: "165",
    Limit: "4",
    Trending: "1",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Kissan Fresh Tomato Ketchup (Bottle)",
    ProductID: "E0502",
    Category: "Snacks & Instant Foods",
    SubCategory: "Spreads, Sauces & Ketchup",
    SubSubCategory: "",
    Unit: "KG",
    Breakqty: "1",
    Price: "160",
    MRP: "160",
    Limit: "4",
    Trending: "1",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Veeba Barbque Sauce",
    ProductID: "E0503",
    Category: "Snacks & Instant Foods",
    SubCategory: "Spreads, Sauces & Ketchup",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "",
    MRP: "",
    Limit: "4",
    Trending: "1",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Veeba Honey Mustard Dressing",
    ProductID: "E0504",
    Category: "Snacks & Instant Foods",
    SubCategory: "Spreads, Sauces & Ketchup",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "",
    MRP: "",
    Limit: "4",
    Trending: "1",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Veeba eggless mayonnaise (Pouch)",
    ProductID: "E0505",
    Category: "Snacks & Instant Foods",
    SubCategory: "Spreads, Sauces & Ketchup",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "",
    MRP: "",
    Limit: "4",
    Trending: "0",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Haldiram's Aloo Bhujia",
    ProductID: "E0601",
    Category: "Snacks & Instant Foods",
    SubCategory: "Snacks & Namkeem",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "",
    MRP: "",
    Limit: "4",
    Trending: "0",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Haldiram's Bhujia",
    ProductID: "E0602",
    Category: "Snacks & Instant Foods",
    SubCategory: "Snacks & Namkeem",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "",
    MRP: "",
    Limit: "4",
    Trending: "0",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Haldiram's Khatta Meetha",
    ProductID: "E0603",
    Category: "Snacks & Instant Foods",
    SubCategory: "Snacks & Namkeem",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "",
    MRP: "",
    Limit: "4",
    Trending: "0",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Bikano Shahi Mixture",
    ProductID: "E0604",
    Category: "Snacks & Instant Foods",
    SubCategory: "Snacks & Namkeem",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "",
    MRP: "",
    Limit: "4",
    Trending: "1",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Act-II Popcorn Butter Delite",
    ProductID: "E0701",
    Category: "Snacks & Instant Foods",
    SubCategory: "Ready to Eat",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "",
    MRP: "",
    Limit: "4",
    Trending: "0",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Knorr Classic Sweet Corn Vegetable Soup",
    ProductID: "E0702",
    Category: "Snacks & Instant Foods",
    SubCategory: "Ready to Eat",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "",
    MRP: "",
    Limit: "4",
    Trending: "1",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Knorr Classic Thick Tomato Soup",
    ProductID: "E0703",
    Category: "Snacks & Instant Foods",
    SubCategory: "Ready to Eat",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "",
    MRP: "",
    Limit: "4",
    Trending: "0",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Act-II Popcorn Classic Salted",
    ProductID: "E0704",
    Category: "Snacks & Instant Foods",
    SubCategory: "Ready to Eat",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "",
    MRP: "",
    Limit: "4",
    Trending: "0",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Cadbury Dairy Milk Silk Chocolate Bar",
    ProductID: "E0801",
    Category: "Snacks & Instant Foods",
    SubCategory: "Chocolates & Candies",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "",
    MRP: "",
    Limit: "4",
    Trending: "1",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Cadbury Dairy Milk Silk Oreo Chocolate Bar",
    ProductID: "E0802",
    Category: "Snacks & Instant Foods",
    SubCategory: "Chocolates & Candies",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "",
    MRP: "",
    Limit: "4",
    Trending: "0",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Cadbury Bournville Raisin & Nut",
    ProductID: "E0803",
    Category: "Snacks & Instant Foods",
    SubCategory: "Chocolates & Candies",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "",
    MRP: "",
    Limit: "4",
    Trending: "1",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Snickers Chocolate Peanut Bar",
    ProductID: "E0804",
    Category: "Snacks & Instant Foods",
    SubCategory: "Chocolates & Candies",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "",
    MRP: "",
    Limit: "4",
    Trending: "1",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Cadbury 5 Star Chocolate Bar",
    ProductID: "E0805",
    Category: "Snacks & Instant Foods",
    SubCategory: "Chocolates & Candies",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "",
    MRP: "",
    Limit: "4",
    Trending: "0",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Mother's Recipe Mango Pickle Hot",
    ProductID: "E0901",
    Category: "Snacks & Instant Foods",
    SubCategory: "Pickles",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "",
    MRP: "",
    Limit: "4",
    Trending: "1",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Mother's Recipe Green Chilli Pickle",
    ProductID: "E0902",
    Category: "Snacks & Instant Foods",
    SubCategory: "Pickles",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "",
    MRP: "",
    Limit: "4",
    Trending: "1",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Mother's Recipe Mixed Pickle",
    ProductID: "E0903",
    Category: "Snacks & Instant Foods",
    SubCategory: "Pickles",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "",
    MRP: "",
    Limit: "4",
    Trending: "0",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Colgate MaxFresh Blue Gel Toothpaste",
    ProductID: "F0101",
    Category: "Beauty & Hygiene",
    SubCategory: "Oral Care",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "150",
    Price: "",
    MRP: "",
    Limit: "4",
    Trending: "0",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Colgate Strong Teeth Toothpaste",
    ProductID: "F0102",
    Category: "Beauty & Hygiene",
    SubCategory: "Oral Care",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "150",
    Price: "",
    MRP: "",
    Limit: "4",
    Trending: "1",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Pepsodent Whitening Toothpaste",
    ProductID: "F0103",
    Category: "Beauty & Hygiene",
    SubCategory: "Oral Care",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "150",
    Price: "",
    MRP: "",
    Limit: "4",
    Trending: "1",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Colgate MaxFresh Red Gel Toothpaste",
    ProductID: "F0104",
    Category: "Beauty & Hygiene",
    SubCategory: "Oral Care",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "150",
    Price: "",
    MRP: "",
    Limit: "4",
    Trending: "0",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Listerine Cool Mint Mouthwash",
    ProductID: "F0105",
    Category: "Beauty & Hygiene",
    SubCategory: "Oral Care",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "150",
    Price: "",
    MRP: "",
    Limit: "4",
    Trending: "1",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Whisper Ultra Clean Sanitary Pads XL Wings",
    ProductID: "F0201",
    Category: "Beauty & Hygiene",
    SubCategory: "Feminine Hygiene",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "150",
    Price: "",
    MRP: "",
    Limit: "4",
    Trending: "1",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Stayfree Secure Cottony Soft Pads XL Wings",
    ProductID: "F0202",
    Category: "Beauty & Hygiene",
    SubCategory: "Feminine Hygiene",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "150",
    Price: "",
    MRP: "",
    Limit: "4",
    Trending: "1",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Veet Hair Removal Cream-Lotus, Milk & Jasmine",
    ProductID: "F0203",
    Category: "Beauty & Hygiene",
    SubCategory: "Feminine Hygiene",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "150",
    Price: "",
    MRP: "",
    Limit: "4",
    Trending: "1",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Veet Easygrip Wax Strips- Dry Skin",
    ProductID: "F0204",
    Category: "Beauty & Hygiene",
    SubCategory: "Feminine Hygiene",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "150",
    Price: "",
    MRP: "",
    Limit: "4",
    Trending: "1",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Durex Extra Time Condoms",
    ProductID: "F0301",
    Category: "Beauty & Hygiene",
    SubCategory: "Health & Medicine",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "150",
    Price: "",
    MRP: "",
    Limit: "4",
    Trending: "1",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Vicks Vaporub",
    ProductID: "F0302",
    Category: "Beauty & Hygiene",
    SubCategory: "Health & Medicine",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "150",
    Price: "",
    MRP: "",
    Limit: "4",
    Trending: "0",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Dettol Antiseptic Liquid",
    ProductID: "F0303",
    Category: "Beauty & Hygiene",
    SubCategory: "Health & Medicine",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "150",
    Price: "",
    MRP: "",
    Limit: "4",
    Trending: "0",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Durex Extra Dots Condoms",
    ProductID: "F0304",
    Category: "Beauty & Hygiene",
    SubCategory: "Health & Medicine",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "150",
    Price: "",
    MRP: "",
    Limit: "4",
    Trending: "0",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Dettol Instant Hand Sanitizer",
    ProductID: "F0401",
    Category: "Beauty & Hygiene",
    SubCategory: "Bath & Hand Wash",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "150",
    Price: "",
    MRP: "",
    Limit: "4",
    Trending: "0",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Cinthol Confidence+ Bath Soap",
    ProductID: "F0402",
    Category: "Beauty & Hygiene",
    SubCategory: "Bath & Hand Wash",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "150",
    Price: "",
    MRP: "",
    Limit: "4",
    Trending: "1",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Pears Pure & Gentle Original Body Wash",
    ProductID: "F0403",
    Category: "Beauty & Hygiene",
    SubCategory: "Bath & Hand Wash",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "150",
    Price: "",
    MRP: "",
    Limit: "4",
    Trending: "0",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Nivea Men Active Clean Shower Gel",
    ProductID: "F0404",
    Category: "Beauty & Hygiene",
    SubCategory: "Bath & Hand Wash",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "150",
    Price: "",
    MRP: "",
    Limit: "4",
    Trending: "1",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Pantene Total Damage Care Shampoo",
    ProductID: "F0501",
    Category: "Beauty & Hygiene",
    SubCategory: "Hair Care",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "150",
    Price: "",
    MRP: "",
    Limit: "4",
    Trending: "0",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "TRESemme Keratin Smooth Shampoo",
    ProductID: "F0502",
    Category: "Beauty & Hygiene",
    SubCategory: "Hair Care",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "150",
    Price: "",
    MRP: "",
    Limit: "4",
    Trending: "0",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Parachute Coconut Oil",
    ProductID: "F0503",
    Category: "Beauty & Hygiene",
    SubCategory: "Hair Care",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "150",
    Price: "",
    MRP: "",
    Limit: "4",
    Trending: "1",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Gillette Mach 3 Razor",
    ProductID: "F0601",
    Category: "Beauty & Hygiene",
    SubCategory: "Men's Grooming",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "150",
    Price: "",
    MRP: "",
    Limit: "4",
    Trending: "0",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Gillette Sensitive Skin Shave Foam",
    ProductID: "F0602",
    Category: "Beauty & Hygiene",
    SubCategory: "Men's Grooming",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "150",
    Price: "",
    MRP: "",
    Limit: "4",
    Trending: "1",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "VI-John Regular Shaving Cream",
    ProductID: "F0603",
    Category: "Beauty & Hygiene",
    SubCategory: "Men's Grooming",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "150",
    Price: "",
    MRP: "",
    Limit: "4",
    Trending: "1",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Fair & Lovely Fairness Cream",
    ProductID: "F0701",
    Category: "Beauty & Hygiene",
    SubCategory: "Skin Care",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "150",
    Price: "",
    MRP: "",
    Limit: "4",
    Trending: "0",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Nivea Soft Moisturizing Cream",
    ProductID: "F0702",
    Category: "Beauty & Hygiene",
    SubCategory: "Skin Care",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "150",
    Price: "",
    MRP: "",
    Limit: "4",
    Trending: "1",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Pond's White Beauty Anti-spot Fairness Cream",
    ProductID: "F0703",
    Category: "Beauty & Hygiene",
    SubCategory: "Skin Care",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "150",
    Price: "",
    MRP: "",
    Limit: "4",
    Trending: "1",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Dabur Gulabari Premium Rose Water",
    ProductID: "F0704",
    Category: "Beauty & Hygiene",
    SubCategory: "Skin Care",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "150",
    Price: "",
    MRP: "",
    Limit: "4",
    Trending: "0",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Nivea Cherry Shine Caring Lip Balm",
    ProductID: "F0801",
    Category: "Beauty & Hygiene",
    SubCategory: "Makeup",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "150",
    Price: "",
    MRP: "",
    Limit: "4",
    Trending: "0",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Lakme Classic Brown Eyeconic Kajal",
    ProductID: "F0802",
    Category: "Beauty & Hygiene",
    SubCategory: "Makeup",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "150",
    Price: "",
    MRP: "",
    Limit: "4",
    Trending: "1",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Lakme Truewear Color Crush Nail Color Shade 58",
    ProductID: "F0803",
    Category: "Beauty & Hygiene",
    SubCategory: "Makeup",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "150",
    Price: "",
    MRP: "",
    Limit: "4",
    Trending: "1",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Lakme Nail Color Remover",
    ProductID: "F0804",
    Category: "Beauty & Hygiene",
    SubCategory: "Makeup",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "150",
    Price: "",
    MRP: "",
    Limit: "4",
    Trending: "0",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Axe Signature Mysterious Body Perfume",
    ProductID: "F0901",
    Category: "Beauty & Hygiene",
    SubCategory: "Fragrances & Deos",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "150",
    Price: "",
    MRP: "",
    Limit: "4",
    Trending: "1",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Denver Hamilton Deodrant Body Spray",
    ProductID: "F0902",
    Category: "Beauty & Hygiene",
    SubCategory: "Fragrances & Deos",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "150",
    Price: "",
    MRP: "",
    Limit: "4",
    Trending: "1",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Nivea Fresh Active Original Deodrant",
    ProductID: "F0903",
    Category: "Beauty & Hygiene",
    SubCategory: "Fragrances & Deos",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "150",
    Price: "",
    MRP: "",
    Limit: "4",
    Trending: "1",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Park Avenue Signature Collection Voyage Perfume Spray",
    ProductID: "F0904",
    Category: "Beauty & Hygiene",
    SubCategory: "Fragrances & Deos",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "150",
    Price: "",
    MRP: "",
    Limit: "4",
    Trending: "1",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Ariel Matic Liquid Detergent",
    ProductID: "G0101",
    Category: "Cleaning & Household",
    SubCategory: "Detergents & Dishwash",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "",
    MRP: "",
    Limit: "4",
    Trending: "1",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Comfort After Wash Lily Fresh Fabric Conditioner",
    ProductID: "G0102",
    Category: "Cleaning & Household",
    SubCategory: "Detergents & Dishwash",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "",
    MRP: "",
    Limit: "4",
    Trending: "1",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Vim Lemon Dishwash Gel",
    ProductID: "G0103",
    Category: "Cleaning & Household",
    SubCategory: "Detergents & Dishwash",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "",
    MRP: "",
    Limit: "4",
    Trending: "0",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Surf Excel Quickwash Detergent Powder",
    ProductID: "G0104",
    Category: "Cleaning & Household",
    SubCategory: "Detergents & Dishwash",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "",
    MRP: "",
    Limit: "4",
    Trending: "0",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Colin Glass Cleaner",
    ProductID: "G0201",
    Category: "Cleaning & Household",
    SubCategory: "All Purpose Cleaners",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "",
    MRP: "",
    Limit: "4",
    Trending: "0",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Harpic Power Plus Toilet Cleaner",
    ProductID: "G0202",
    Category: "Cleaning & Household",
    SubCategory: "All Purpose Cleaners",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "",
    MRP: "",
    Limit: "4",
    Trending: "0",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Lizol Disinfectant Citrus Surface Cleaner",
    ProductID: "G0203",
    Category: "Cleaning & Household",
    SubCategory: "All Purpose Cleaners",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "",
    MRP: "",
    Limit: "4",
    Trending: "1",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Harpic Disinfectant Bathroom Cleaner- Lemon",
    ProductID: "G0204",
    Category: "Cleaning & Household",
    SubCategory: "All Purpose Cleaners",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "",
    MRP: "",
    Limit: "4",
    Trending: "0",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Harpic Flushmatic Aquamarine Toilet Block",
    ProductID: "G0205",
    Category: "Cleaning & Household",
    SubCategory: "All Purpose Cleaners",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "",
    MRP: "",
    Limit: "4",
    Trending: "1",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Apsara Platinum Extra Dark Pencil",
    ProductID: "G0301",
    Category: "Cleaning & Household",
    SubCategory: "Stationary",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "",
    MRP: "",
    Limit: "4",
    Trending: "0",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Nataraj Pencil",
    ProductID: "G0302",
    Category: "Cleaning & Household",
    SubCategory: "Stationary",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "",
    MRP: "",
    Limit: "4",
    Trending: "0",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Reynolds Trimax Pen",
    ProductID: "G0303",
    Category: "Cleaning & Household",
    SubCategory: "Stationary",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "",
    MRP: "",
    Limit: "4",
    Trending: "1",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Nataraj Eraser",
    ProductID: "G0304",
    Category: "Cleaning & Household",
    SubCategory: "Stationary",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "",
    MRP: "",
    Limit: "4",
    Trending: "0",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Origami So Soft 3 Ply- Tissue Roll",
    ProductID: "G0401",
    Category: "Cleaning & Household",
    SubCategory: "Disposables & Garbage Bags",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "",
    MRP: "",
    Limit: "4",
    Trending: "1",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Origami Klassic Plain Cocktail Napkins",
    ProductID: "G0402",
    Category: "Cleaning & Household",
    SubCategory: "Disposables & Garbage Bags",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "",
    MRP: "",
    Limit: "4",
    Trending: "1",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Hindalco Freshwrapp Standard Aluminium Foil",
    ProductID: "G0403",
    Category: "Cleaning & Household",
    SubCategory: "Disposables & Garbage Bags",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "",
    MRP: "",
    Limit: "4",
    Trending: "0",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Kara Face Wipes- Aloe Mint",
    ProductID: "G0404",
    Category: "Cleaning & Household",
    SubCategory: "Disposables & Garbage Bags",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "",
    MRP: "",
    Limit: "4",
    Trending: "1",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Godrej Good Knight Power Active+ Mosquito Repellent Combo",
    ProductID: "G0501",
    Category: "Cleaning & Household",
    SubCategory: "Freshness & Repellents",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "",
    MRP: "",
    Limit: "4",
    Trending: "1",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "HIT Mosquito & Fly Killer Spray",
    ProductID: "G0502",
    Category: "Cleaning & Household",
    SubCategory: "Freshness & Repellents",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "",
    MRP: "",
    Limit: "4",
    Trending: "1",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "HIT Cockroach Killer Spray",
    ProductID: "G0503",
    Category: "Cleaning & Household",
    SubCategory: "Freshness & Repellents",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "",
    MRP: "",
    Limit: "4",
    Trending: "1",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Godrej Aer Spray Freshner- Violet Valley Bloom",
    ProductID: "G0504",
    Category: "Cleaning & Household",
    SubCategory: "Freshness & Repellents",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "",
    MRP: "",
    Limit: "4",
    Trending: "0",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Godrej Aer Spray Freshner- Fresh Lush Green",
    ProductID: "G0505",
    Category: "Cleaning & Household",
    SubCategory: "Freshness & Repellents",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "",
    MRP: "",
    Limit: "4",
    Trending: "0",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Scotch Brite Scrub Pad Large",
    ProductID: "G0601",
    Category: "Cleaning & Household",
    SubCategory: "Mops, Brushes & Cleaners",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "",
    MRP: "",
    Limit: "4",
    Trending: "0",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Scotch Brite Super Strong Scrub Pad",
    ProductID: "G0602",
    Category: "Cleaning & Household",
    SubCategory: "Mops, Brushes & Cleaners",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "",
    MRP: "",
    Limit: "4",
    Trending: "0",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Scotch Brite Scrub Sponge Small",
    ProductID: "G0603",
    Category: "Cleaning & Household",
    SubCategory: "Mops, Brushes & Cleaners",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "",
    MRP: "",
    Limit: "4",
    Trending: "1",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Cherry Blossom Black Shoe Polish",
    ProductID: "G0701",
    Category: "Cleaning & Household",
    SubCategory: "Shoe care",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "",
    MRP: "",
    Limit: "4",
    Trending: "0",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Kiwi Black Paste Shoe Polish",
    ProductID: "G0702",
    Category: "Cleaning & Household",
    SubCategory: "Shoe care",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "",
    MRP: "",
    Limit: "4",
    Trending: "1",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Cherry Blossom Brown, Dark Tan Shoe Polish",
    ProductID: "G0703",
    Category: "Cleaning & Household",
    SubCategory: "Shoe care",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "",
    MRP: "",
    Limit: "4",
    Trending: "0",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Cherry Blossom Black Liquid Shoe Polish",
    ProductID: "G0704",
    Category: "Cleaning & Household",
    SubCategory: "Shoe care",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "",
    MRP: "",
    Limit: "4",
    Trending: "0",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Mangaldeep Deluxe Puja Dhoop",
    ProductID: "G0801",
    Category: "Cleaning & Household",
    SubCategory: "Puja Essentials",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "",
    MRP: "",
    Limit: "4",
    Trending: "1",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Mangaldeep Sandal Puja Dhoop",
    ProductID: "G0802",
    Category: "Cleaning & Household",
    SubCategory: "Puja Essentials",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "",
    MRP: "",
    Limit: "4",
    Trending: "0",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Mangaldeep Sandal Puja Agarbattis",
    ProductID: "G0803",
    Category: "Cleaning & Household",
    SubCategory: "Puja Essentials",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "",
    MRP: "",
    Limit: "4",
    Trending: "1",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Mangaldeep Temple- Lord Jagannath's Favourite Fragrances",
    ProductID: "G0804",
    Category: "Cleaning & Household",
    SubCategory: "Puja Essentials",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "",
    MRP: "",
    Limit: "4",
    Trending: "1",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Eggs Table Tray",
    ProductID: "H0101",
    Category: "Eggs, Meat & Fish",
    SubCategory: "Eggs",
    SubSubCategory: "",
    Unit: "PCS",
    Breakqty: "30",
    Price: "",
    MRP: "",
    Limit: "4",
    Trending: "0",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Eggs-Regular",
    ProductID: "H0102",
    Category: "Eggs, Meat & Fish",
    SubCategory: "Eggs",
    SubSubCategory: "",
    Unit: "PCS",
    Breakqty: "6",
    Price: "",
    MRP: "",
    Limit: "4",
    Trending: "1",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Chicken-Curry Cut Without Skin",
    ProductID: "H0201",
    Category: "Eggs, Meat & Fish",
    SubCategory: "Poultry",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "",
    MRP: "",
    Limit: "4",
    Trending: "1",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Chicken Breast-Boneless",
    ProductID: "H0202",
    Category: "Eggs, Meat & Fish",
    SubCategory: "Poultry",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "",
    MRP: "",
    Limit: "4",
    Trending: "0",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Chicken Mince",
    ProductID: "H0203",
    Category: "Eggs, Meat & Fish",
    SubCategory: "Poultry",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "",
    MRP: "",
    Limit: "4",
    Trending: "0",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Chicken-Leg Piece",
    ProductID: "H0204",
    Category: "Eggs, Meat & Fish",
    SubCategory: "Poultry",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "",
    MRP: "",
    Limit: "4",
    Trending: "1",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "King Fish(Medium)-Boneless",
    ProductID: "H0301",
    Category: "Eggs, Meat & Fish",
    SubCategory: "Fish & Seafood",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "",
    MRP: "",
    Limit: "4",
    Trending: "0",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Uncle Sams Frozen Basa Fish- Fillets",
    ProductID: "H0302",
    Category: "Eggs, Meat & Fish",
    SubCategory: "Fish & Seafood",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "",
    MRP: "",
    Limit: "4",
    Trending: "1",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Frozen White Prawns- Medium",
    ProductID: "H0303",
    Category: "Eggs, Meat & Fish",
    SubCategory: "Fish & Seafood",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "",
    MRP: "",
    Limit: "4",
    Trending: "1",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Mutton-Curry Cut",
    ProductID: "H0401",
    Category: "Eggs, Meat & Fish",
    SubCategory: "Mutton & Lamb",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "",
    MRP: "",
    Limit: "4",
    Trending: "0",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Mutton- Masala Seek Kebab",
    ProductID: "H0402",
    Category: "Eggs, Meat & Fish",
    SubCategory: "Mutton & Lamb",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "",
    MRP: "",
    Limit: "4",
    Trending: "1",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Lamb- Curry Cut",
    ProductID: "H0403",
    Category: "Eggs, Meat & Fish",
    SubCategory: "Mutton & Lamb",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "250",
    Price: "",
    MRP: "",
    Limit: "4",
    Trending: "1",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Nestle NAN Pro 1 Infant Formula",
    ProductID: "I0101",
    Category: "Baby Care",
    SubCategory: "Baby Food",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "400",
    Price: "610",
    MRP: "610",
    Limit: "4",
    Trending: "1",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Nestle Lactogen 2 Follow Up Infant Formula Powder",
    ProductID: "I0102",
    Category: "Baby Care",
    SubCategory: "Baby Food",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "400",
    Price: "320",
    MRP: "320",
    Limit: "4",
    Trending: "0",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Nestle Cerelac Multigrain Dal Veg Baby Cereal",
    ProductID: "I0103",
    Category: "Baby Care",
    SubCategory: "Baby Food",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "300",
    Price: "252",
    MRP: "252",
    Limit: "4",
    Trending: "1",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Pampers Baby Dry Pants Diapers (M)",
    ProductID: "I0201",
    Category: "Baby Care",
    SubCategory: "Diapers & Wipes",
    SubSubCategory: "",
    Unit: "PCS",
    Breakqty: "76",
    Price: "945",
    MRP: "945",
    Limit: "4",
    Trending: "1",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Mamy Poko Pants Standard Diapers (M)",
    ProductID: "I0202",
    Category: "Baby Care",
    SubCategory: "Diapers & Wipes",
    SubSubCategory: "",
    Unit: "PCS",
    Breakqty: "18",
    Price: "",
    MRP: "",
    Limit: "4",
    Trending: "0",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Huggies Wonder Pants Diapers (XL)",
    ProductID: "I0203",
    Category: "Baby Care",
    SubCategory: "Diapers & Wipes",
    SubSubCategory: "",
    Unit: "PCS",
    Breakqty: "16",
    Price: "",
    MRP: "",
    Limit: "4",
    Trending: "1",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Himalaya Baby Cream",
    ProductID: "I0301",
    Category: "Baby Care",
    SubCategory: "Baby Bath Care",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "200",
    Price: "248",
    MRP: "260",
    Limit: "4",
    Trending: "0",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Johnson's No More Tears Baby Shampoo",
    ProductID: "I0302",
    Category: "Baby Care",
    SubCategory: "Baby Bath Care",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "475",
    Price: "342",
    MRP: "360",
    Limit: "4",
    Trending: "0",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Johnson's Baby Lotion",
    ProductID: "I0303",
    Category: "Baby Care",
    SubCategory: "Baby Bath Care",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "100",
    Price: "",
    MRP: "",
    Limit: "4",
    Trending: "1",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
  {
    ProductName: "Himalaya Baby Powder",
    ProductID: "I0304",
    Category: "Baby Care",
    SubCategory: "Baby Bath Care",
    SubSubCategory: "",
    Unit: "GM",
    Breakqty: "400",
    Price: "185",
    MRP: "200",
    Limit: "4",
    Trending: "1",
    field12: "",
    Grofers: "",
    Bigbasket: "",
    Milkbasket: "",
    Other_Startups: "",
  },
];
